apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: e2etesting
data:
  mosquitto.conf: |-
    log_dest stdout
    # Ip/hostname to listen to.
    # If not given, will listen on all interfaces
    #bind_address
    # Port to use for the default listener.
    listener 1883
    # Allow anonymous users to connect?
    # If not, the password file should be created
    allow_anonymous true
    persistence false
    #persistence_location /tmp/mosquitto/data
    #log_dest file /var/log/mosquitto/mosquitto.log
    log_dest topic
    log_type error
    log_type warning
    log_type notice
    log_type information
    # If set to true, client connection and disconnection messages will be included in the log.
    connection_messages true
    # If set to true, add a timestamp value to each log message.
    log_timestamp true