{{- $opcuabrokerLabels := include "opcuabroker.labels" . -}}
{{- $opcuabrokerSelectorLabels := include "opcuabroker.selectorLabels" . -}}
{{- $releaseName := .Release.Name -}}

{{ range $i := until (.Values.simulations | int) }}
{{ $suffix := printf "%s-%06d" $releaseName $i }}
apiVersion: v1
kind: Service
metadata:
  name: opcplc-{{ $suffix }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $opcuabrokerLabels | nindent 4 }}
    app.kubernetes.io/component: opcplc-{{ $suffix }}-service
spec:
  type: ClusterIP
  selector:
    {{- $opcuabrokerSelectorLabels | nindent 4 }}
    app.kubernetes.io/component: opcplc-{{ $suffix }}
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
---
{{ end }}
