apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opcuabroker.configmap" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opcuabroker.labels" . | nindent 4 }}
data:
  nodesfile.json: |-
    {
      "Folder": "MyTelemetry",
      "NodeList": [
        {
          "NodeId": "panic",
          "Name": "Panic",
          "DataType": "Boolean",
          "ValueRank": -1,
          "AccessLevel": "CurrentReadOrWrite",
          "Description": "Node that panics, if written"
        }
      ]
    }
