{
 "title": "Publisher",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Publisher - Messages ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "iiot_edge_publisher_messages{}", "legendFormat": "Messages sent" }
   ]
  },
  {
   "title": "Publisher - Messages send duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.985, sum(rate(iiot_edge_publisher_messages_duration_bucket[5m])) by (le))",
     "legendFormat": "98.5th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(iiot_edge_publisher_messages_duration_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(iiot_edge_publisher_messages_duration_bucket[5m])) by (le))",
     "legendFormat": "80th percentile"
    }
   ]
  },
  {
   "title": "Publisher - Dropped count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iiot_edge_publisher_iothub_queue_dropped_count{}"
    }
   ]
  },
  {
   "title": "Publisher - Dotnet GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_gc_heap_size{}[$__interval])",
     "legendFormat": "GC {{generation}}"
    }
   ]
  },
  {
   "title": "Publisher - Chunk Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iiot_edge_publisher_chunk_size_average",
     "legendFormat": "Average chunk size"
    }
   ]
  },
  {
   "title": "Publisher - Data Changes per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iiot_edge_publisher_data_changes_per_second{}"
    }
   ]
  },
  {
   "title": "Publisher - Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iiot_edge_publisher_iothub_queue_size{}",
     "legendFormat": "Queue Size"
    }
   ]
  }
 ]
}