#!/usr/bin/env bash

# Debug|Release
CONFIGURATION=Release

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"
check_dependency_dotnet

cd $APP_HOME

dotnet restore --verbosity=quiet

cd ProxyAgent
dotnet run --configuration $CONFIGURATION --project ProxyAgent.csproj

set +e