# Default values for Azure Industrial-IoT solution.

# Details of Docker images.
image:
  # image.registry is URL of Docker registry from where images will be pulled.
  registry: mcr.microsoft.com/iot
  # image.tag defines which version of Docker images to pull.
  tag: 2.5.2
  # image.pullPolicy defines value of imagePullPolicy of deployments.
  pullPolicy: IfNotPresent

Azure:
  TenantId: null

  IoTHub:
    Name: null

    EventHub:
      Endpoint: null
      PartitionCount: null
      ConsumerGroup: null

    SharedAccessPolicies:
      iothubowner:
        ConnectionString: null

  CosmosDB:
    ConnectionString: null

  StorageAccount:
    Name: null
    AccessKey: null
    EndpointSuffix: core.windows.net

  EventHubNamespace:
    SharedAccessPolicies:
      RootManageSharedAccessKey:
        ConnectionString: null

    EventHub:
      Name: null

  ServiceBusNamespace:
    SharedAccessPolicies:
      RootManageSharedAccessKey:
        ConnectionString: null

  KeyVault:
    URI: null

  LogAnalyticsWorkspace:
    Name: null

  ApplicationInsights:
    Name: null
    InstrumentationKey: null

  AppService:
    URL: null

  SignalR:
    ConnectionString: null

  ServicesApp:
    CorsWhitelist: '*'
    Auth:
      HttpsRedirectPort: 0
      Required: true
      Audience: null

  ClientsApp:
    Auth:
      AadAppId: null
      Authority: https://login.microsoftonline.com/

deployment:
  microServices:
    registry:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    twin:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    history:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    gateway:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    vault:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    alerting:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    onboarding:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    jobs:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    modelProcessor:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    blobNotification:
      enabled: true
      replicas: 1
      # extraArgs: []
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "250m"

  ingress:
    tls:
      crt: null
      key: null