schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

stages:
- stage: build
  displayName: 'Build and Test Code'
  jobs:
  - template: tools/templates/ci.yml
  - template: tools/templates/sdl.yml
- stage: pack
  displayName: 'Package and Sign Nuget'
  dependsOn:
  - build
  jobs:
  - template: tools/templates/nuget.yml
    parameters:
      sign: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}
- stage: iiot_deployment
  displayName: 'Publish Microsoft.Azure.IIoT.Deployment'
  dependsOn:
  - build
  jobs:
  - template: tools/templates/iiot_deployment_win.yml
    parameters:
      sign: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}
  - template: tools/templates/iiot_deployment_linux.yml
  - template: tools/templates/iiot_deployment_mac.yml
- stage: images
  displayName: 'Create and Push Images'
  dependsOn:
  - pack
  - iiot_deployment
  jobs:
  - template: tools/templates/acrbuild.yml
    parameters:
      useNugets: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}
- stage: simulation
  displayName: Create or update simulation environment
  jobs:
  - template: tools/templates/simulation_linux.yml
  - template: tools/templates/simulation_windows.yml
