schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

stages:
- stage: deploy
  displayName: 'Create and Push Images and redeploy'
  jobs:
  - template: tools/templates/acrbuild.yml
  - template: tools/templates/simulation_linux.yml
  - template: tools/templates/simulation_windows.yml
