version: '3'
services:
  registryservice:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-registry-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    ports:
      - "9042:9042"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_IOTHUB_CONNSTRING
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  twinservice:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-twin-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    ports:
      - "9041:9041"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  historyservice:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-history-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.OpcUa.History/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    ports:
      - "9043:9043"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  gatewayservice:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-gateway-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.OpcUa.Gateway/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    ports:
      - "9040:9040"
      - "51111:51111"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  vaultservice:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-vault-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.OpcUa.Vault/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    ports:
      - "9044:9044"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  alertingservice:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-alerting-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.OpcUa.Alerting/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    environment:
      - PCS_KEYVAULT_URL
      - PCS_WORKSPACE_NAME
      - PCS_IOTHUB_CONNSTRING
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  onboardingservice:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-onboarding-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.OpcUa.Onboarding/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  jobsservice:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-jobs-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.OpcUa.Jobs/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  modelprocessor:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-processor-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.OpcUa.Processor/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  blobnotification:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}blob-notification-service:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./services/src/Microsoft.Azure.IIoT.Services.Notification.Blob/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_EVENTHUB_CONNSTRING
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  twinmodulehost:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-twin:host-${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./modules/opc-twin/docker/${IMAGE_OS:-linux}/amd64/Dockerfile.host
    network_mode: "${HOST_NETWORK:-host}"
    cap_add:
      - NET_ADMIN
    environment:
      - PCS_KEYVAULT_URL
      - PCS_IOTHUB_CONNSTRING
  twinmodule:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-twin:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./modules/opc-twin/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
  publishermodule:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-publisher:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./modules/opc-publisher/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    ports:
      - "62222:62222"
    environment:
      - _HUB_CS
    command: --aa
  opcserver0:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-testing:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Testing/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    hostname: opcserver0
    command: --sample -p 51210
    ports:
      - "51210:51210"
  opcserver1:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-testing:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Testing/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    hostname: opcserver1
    command: --sample -p 51211
    ports:
      - "51211:51211"
  opcserver2:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-testing:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Testing/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    hostname: opcserver2
    command: --sample -p 51212
    ports:
      - "51212:51212"
  twinconsole:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-api:${IMAGE_VERSION:-latest}
    build: 
      context: .
      dockerfile: ./api/src/Microsoft.Azure.IIoT.OpcUa.Api/docker/${IMAGE_OS:-linux}/amd64/Dockerfile
    command: exit
    environment:
      - PCS_KEYVAULT_URL
      - PCS_TWIN_REGISTRY_URL=http://twinregistry:9042
      - PCS_TWIN_SERVICE_URL=http://twinservice:9041
      - PCS_VAULT_SERVICE_URL=http://vaultservice:9044
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_WEBUI_AUTH_AAD_INSTANCE
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
