FROM microsoft/dotnet:2.1-sdk-stretch-arm32v7 AS build-env

COPY /src /build/src

WORKDIR /build/src
RUN dotnet restore
RUN dotnet publish --configuration Release --output /build/out

FROM microsoft/dotnet:2.1-runtime-stretch-arm32v7

COPY --from=build-env /build/out /build/out
WORKDIR /docker
ENTRYPOINT ["dotnet", "/build/out/OpcPublisher.dll"]