FROM microsoft/dotnet:1.1-sdk-nanoserver

COPY / /build

WORKDIR /build
RUN dotnet restore

WORKDIR /build/src/GatewayApp.NetCore
RUN dotnet publish -c Debug -f netcoreapp1.1 -r win10-x64 -o bin/Debug/netcoreapp1.1

WORKDIR /build/src/GatewayApp.NetCore/bin/Debug/netcoreapp1.1
RUN dir
ENV PATH=/build/src/GatewayApp.NetCore/bin/Debug/netcoreapp1.1
ENTRYPOINT ["./GatewayApp.NetCore"]