version: '3'
services:
  application:
    build:
      context: .
      dockerfile: ./deploy/docker/application/Dockerfile
    ports:
      - "5000:80"
  platform:
    build:
      context: .
      dockerfile: ./deploy/docker/platform/Dockerfile
    ports:
      - "9080:80"
