FROM microsoft/dotnet:2.0-sdk AS build-env

COPY /src /build/src
WORKDIR /build/src
RUN dotnet restore
RUN dotnet publish --configuration Release --output /build/out

FROM microsoft/dotnet:2.0-runtime
WORKDIR /docker
COPY --from=build-env /build/out ./
ENTRYPOINT ["dotnet", "OpcPublisher.dll"]
