version: '3'
services:
  registryservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-registry-service:${SERVICES_VERSION:-latest}
    ports:
      - "9042:9042"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_IOTHUB_CONNSTRING
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  twinservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-twin-service:${SERVICES_VERSION:-latest}
    ports:
      - "9041:9041"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  historyservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-history-service:${SERVICES_VERSION:-latest}
    ports:
      - "9043:9043"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  gatewayservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-gateway-service:${SERVICES_VERSION:-latest}
    ports:
      - "9040:9040"
      - "51111:51111"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  vaultservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-vault-service:${SERVICES_VERSION:-latest}
    ports:
      - "9044:9044"
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  alertingservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-alerting-service:${SERVICES_VERSION:-latest}
    environment:
      - PCS_KEYVAULT_URL
      - PCS_WORKSPACE_NAME
      - PCS_IOTHUB_CONNSTRING
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  onboardingservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-onboarding-service:${SERVICES_VERSION:-latest}
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  jobsservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-jobs-service:${SERVICES_VERSION:-latest}
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  modelprocessor:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-processor-service:${SERVICES_VERSION:-latest}
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
  blobnotification:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/blob-notification-service:${SERVICES_VERSION:-latest}
    environment:
      - PCS_KEYVAULT_URL
      - PCS_SERVICEBUS_CONNSTRING
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_EVENTHUB_CONNSTRING
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_APPINSIGHTS_NAME
      - PCS_APPINSIGHTS_INSTRUMENTATIONKEY
