apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: industrial-iot-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: industrial-iot-role
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - namespaces
  verbs:
  - get
