apiVersion: v1
kind: Secret
metadata:
  name: {{ template "industrial-iot.env.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: industrial-iot-env
    app.kubernetes.io/part-of: industrial-iot
type: Opaque
data:
  _HUB_CS: {{ .Values.IoTHub.SharedAccessPolicies.iothubowner.ConnectionString | b64enc }}
  PCS_IOTHUB_CONNSTRING: {{ .Values.IoTHub.SharedAccessPolicies.iothubowner.ConnectionString | b64enc }}
  PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING: {{ .Values.CosmosDB.ConnectionString | b64enc }}
  PCS_TELEMETRY_DOCUMENTDB_CONNSTRING: {{ .Values.CosmosDB.ConnectionString | b64enc }}
  PCS_TELEMETRYAGENT_DOCUMENTDB_CONNSTRING: {{ .Values.CosmosDB.ConnectionString | b64enc }}
  PCS_IOTHUBREACT_ACCESS_CONNSTRING: {{ .Values.IoTHub.SharedAccessPolicies.iothubowner.ConnectionString | b64enc }}
  PCS_IOTHUBREACT_HUB_NAME: {{ .Values.IoTHub.Name | b64enc }}
  PCS_IOTHUBREACT_HUB_ENDPOINT: {{ .Values.IoTHub.EventHub.Endpoint | b64enc }}
  PCS_IOTHUBREACT_HUB_CONSUMERGROUP: {{ .Values.IoTHub.EventHub.ConsumerGroup | b64enc }}
  PCS_IOTHUBREACT_HUB_PARTITIONS: {{ printf "%d" ( int64 .Values.IoTHub.EventHub.PartitionCount ) | b64enc }}
  PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT: {{ .Values.StorageAccount.Name | b64enc }}
  PCS_IOTHUBREACT_AZUREBLOB_KEY: {{ .Values.StorageAccount.AccessKey | b64enc }}
  PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX: {{ .Values.StorageAccount.EndpointSuffix | b64enc }}
  PCS_ASA_DATA_AZUREBLOB_ACCOUNT: {{ .Values.StorageAccount.Name | b64enc }}
  PCS_ASA_DATA_AZUREBLOB_KEY: {{ .Values.StorageAccount.AccessKey | b64enc }}
  PCS_ASA_DATA_AZUREBLOB_ENDPOINT_SUFFIX: {{ .Values.StorageAccount.EndpointSuffix | b64enc }}
  PCS_EVENTHUB_CONNSTRING: {{ .Values.EventHubNamespace.SharedAccessPolicies.RootManageSharedAccessKey.ConnectionString | b64enc }}
  PCS_EVENTHUB_NAME: {{ .Values.EventHubNamespace.EventHub.Name | b64enc }}
  PCS_SERVICEBUS_CONNSTRING: {{ .Values.ServiceBusNamespace.SharedAccessPolicies.RootManageSharedAccessKey.ConnectionString | b64enc }}
  PCS_KEYVAULT_URL: {{ .Values.KeyVault.URI | b64enc }}
  PCS_WORKSPACE_NAME: {{ .Values.LogAnalyticsWorkspace.Name | b64enc }}
  PCS_APPINSIGHTS_NAME: {{ .Values.ApplicationInsights.Name | b64enc }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.ApplicationInsights.InstrumentationKey | b64enc }}
  PCS_SERVICE_URL: {{ .Values.AppService.URL | b64enc }}
  PCS_SIGNALR_CONNSTRING: {{ .Values.SignalR.ConnectionString | b64enc }}
  PCS_AUTH_HTTPSREDIRECTPORT: {{ printf "%d" ( int64 .Values.Services.Auth.HttpsRedirectPort ) | b64enc }}
  PCS_AUTH_REQUIRED: {{ printf "%t" .Values.Services.Auth.Required | b64enc }}
  PCS_AUTH_AUDIENCE: {{ .Values.Services.Auth.Audience | b64enc }}
  PCS_AUTH_ISSUER: {{ printf "https://sts.windows.net/%s/" .Values.TenantId | b64enc }}
  PCS_WEBUI_AUTH_AAD_APPID: {{ .Values.Clients.Auth.AadAppId | b64enc }}
  PCS_WEBUI_AUTH_AAD_AUTHORITY: {{ .Values.Clients.Auth.Authority | b64enc }}
  PCS_WEBUI_AUTH_AAD_TENANT: {{ .Values.TenantId | b64enc }}
  PCS_CORS_WHITELIST: {{ .Values.Services.CorsWhitelist | b64enc }}
  REACT_APP_PCS_AUTH_REQUIRED: {{ printf "%t" .Values.Services.Auth.Required | b64enc }}
  REACT_APP_PCS_AUTH_AUDIENCE: {{ .Values.Services.Auth.Audience | b64enc }}
  REACT_APP_PCS_AUTH_ISSUER: {{ printf "https://sts.windows.net/%s/" .Values.TenantId | b64enc }}
  REACT_APP_PCS_WEBUI_AUTH_AAD_APPID: {{ .Values.Clients.Auth.AadAppId | b64enc }}
  REACT_APP_PCS_WEBUI_AUTH_AAD_AUTHORITY: {{ .Values.Clients.Auth.Authority | b64enc }}
  REACT_APP_PCS_WEBUI_AUTH_AAD_TENANT: {{ .Values.TenantId | b64enc }}
