apiVersion: v1
kind: Secret
metadata:
  name: industrial-iot-env
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: industrial-iot-env
    app.kubernetes.io/part-of: industrial-iot
type: Opaque
data:
  _HUB_CS: {{ .Values.IoTHub.SharedAccessPolicies.iothubowner.ConnectionString }}
  PCS_IOTHUB_CONNSTRING: {{ .Values.IoTHub.SharedAccessPolicies.iothubowner.ConnectionString }}
  PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING: {{ .Values.CosmosDB.ConnectionString }}
  PCS_TELEMETRY_DOCUMENTDB_CONNSTRING: {{ .Values.CosmosDB.ConnectionString }}
  PCS_TELEMETRYAGENT_DOCUMENTDB_CONNSTRING: {{ .Values.CosmosDB.ConnectionString }}
  PCS_IOTHUBREACT_ACCESS_CONNSTRING: {{ .Values.IoTHub.SharedAccessPolicies.iothubowner.ConnectionString }}
  PCS_IOTHUBREACT_HUB_NAME: {{ .Values.IoTHub.Name }}
  PCS_IOTHUBREACT_HUB_ENDPOINT: {{ .Values.IoTHub.EventHub.Endpoint }}
  PCS_IOTHUBREACT_HUB_CONSUMERGROUP: {{ .Values.IoTHub.EventHub.ConsumerGroup }}
  PCS_IOTHUBREACT_HUB_PARTITIONS: {{ .Values.IoTHub.EventHub.PartitionCount }}
  PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT: {{ .Values.StorageAccount.Name }}
  PCS_IOTHUBREACT_AZUREBLOB_KEY: {{ .Values.StorageAccount.AccessKey }}
  PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX: {{ .Values.StorageAccount.EndpointSuffix }}
  PCS_ASA_DATA_AZUREBLOB_ACCOUNT: {{ .Values.StorageAccount.Name }}
  PCS_ASA_DATA_AZUREBLOB_KEY: {{ .Values.StorageAccount.AccessKey }}
  PCS_ASA_DATA_AZUREBLOB_ENDPOINT_SUFFIX: {{ .Values.StorageAccount.EndpointSuffix }}
  PCS_EVENTHUB_CONNSTRING: {{ .Values.EventHubNamespace.SharedAccessPolicies.RootManageSharedAccessKey.ConnectionString }}
  PCS_EVENTHUB_NAME: {{ .Values.EventHubNamespace.EventHub.Name }}
  PCS_SERVICEBUS_CONNSTRING: {{ .Values.ServiceBusNamespace.SharedAccessPolicies.RootManageSharedAccessKey.ConnectionString }}
  PCS_KEYVAULT_URL: {{ .Values.KeyVault.URI }}
  PCS_WORKSPACE_NAME: {{ .Values.LogAnalyticsWorkspace.Name }}
  PCS_APPINSIGHTS_NAME: {{ .Values.ApplicationInsights.Name }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.ApplicationInsights.InstrumentationKey }}
  PCS_SERVICE_URL: {{ .Values.AppService.URL }}
  PCS_SIGNALR_CONNSTRING: {{ .Values.SignalR.ConnectionString }}
  PCS_AUTH_HTTPSREDIRECTPORT: {{ .Values.Services.Auth.HttpsRedirectPort }}
  PCS_AUTH_REQUIRED: {{ .Values.Services.Auth.Required }}
  PCS_AUTH_AUDIENCE: {{ .Values.Services.Auth.Audience }}
  PCS_AUTH_ISSUER: https://sts.windows.net/{{ .Values.TenantId }}/
  PCS_WEBUI_AUTH_AAD_APPID: {{ .Values.Clients.Auth.AadAppId }}
  PCS_WEBUI_AUTH_AAD_AUTHORITY: {{ .Values.Clients.Auth.Authority }}
  PCS_WEBUI_AUTH_AAD_TENANT: {{ .Values.TenantId }}
  PCS_CORS_WHITELIST: {{ .Values.Services.CorsWhitelist | quote }}
  REACT_APP_PCS_AUTH_REQUIRED: {{ .Values.Services.Auth.Required }}
  REACT_APP_PCS_AUTH_AUDIENCE: {{ .Values.Services.Auth.Audience }}
  REACT_APP_PCS_AUTH_ISSUER: https://sts.windows.net/{{ .Values.TenantId }}/
  REACT_APP_PCS_WEBUI_AUTH_AAD_APPID: {{ .Values.Clients.Auth.AadAppId }}
  REACT_APP_PCS_WEBUI_AUTH_AAD_AUTHORITY: {{ .Values.Clients.Auth.Authority }}
  REACT_APP_PCS_WEBUI_AUTH_AAD_TENANT: {{ .Values.TenantId }}
