apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-notification-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: blob-notification-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blob-notification-service
      app.kubernetes.io/part-of: industrial-iot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blob-notification-service
        app.kubernetes.io/part-of: industrial-iot
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      serviceAccountName: industrial-iot-serviceaccount
      containers:
      - name: blob-notification-service-container
        image: {{ .Values.Image.Registry }}/blob-notification-service:{{ .Values.Image.Tag }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: PCS_KEYVAULT_URL
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_KEYVAULT_URL
        - name: PCS_IOTHUB_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_IOTHUB_CONNSTRING
        - name: PCS_SERVICEBUS_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_SERVICEBUS_CONNSTRING
        - name: PCS_EVENTHUB_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_EVENTHUB_CONNSTRING
        - name: PCS_IOTHUBREACT_HUB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_IOTHUBREACT_HUB_ENDPOINT
        - name: PCS_IOTHUBREACT_HUB_PARTITIONS
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_IOTHUBREACT_HUB_PARTITIONS
        - name: PCS_IOTHUBREACT_HUB_NAME
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_IOTHUBREACT_HUB_NAME
        - name: PCS_IOTHUBREACT_HUB_CONSUMERGROUP
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_IOTHUBREACT_HUB_CONSUMERGROUP
        - name: PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
        - name: PCS_IOTHUBREACT_AZUREBLOB_KEY
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_IOTHUBREACT_AZUREBLOB_KEY
        - name: PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
        - name: PCS_APPINSIGHTS_NAME
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_APPINSIGHTS_NAME
        - name: PCS_APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_APPINSIGHTS_INSTRUMENTATIONKEY
