apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: opc-vault
    app.kubernetes.io/part-of: industrial-iot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ template "industrial-iot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: opc-vault
    app.kubernetes.io/part-of: industrial-iot
  ports:
  - port: 443
    protocol: TCP
    name: https
  - port: 9044
    protocol: TCP
    name: rest
