{{ if .Values.Deployment.Ingress.tls.crt }}
{{ if .Values.Deployment.Ingress.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: default-ssl-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: industrial-iot
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.Deployment.Ingress.tls.crt }}
  tls.key: {{ .Values.Deployment.Ingress.tls.key }}
{{ end }}
{{ end }}