apiVersion: v1
kind: Service
metadata:
  name: verifier
  namespace: e2etesting
spec:
  selector:
    app: verifier
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  type: LoadBalancer