version: "3.9"
services:
  ############################
  # OPC PLC Simulation
  ############################
  opcplc:
    hostname: opcplc
    command: [
      "--sph=True",
      "--spf=/shared/pn.json",
      "--pn=50000",
      "--alm=True",
      "--ses=True",
      "--fn=10000",
      "--sn=10000",
      "--aa=True",
      "--ut=True"
      ]
  ############################
  # Network capture
  ############################
  pcap:
    container_name: pcap
    image: travelping/pcap
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - dump:/data
    environment:
      IFACE: any
      FORMAT: pcapng
      MAXFILENUM: 5
      MAXFILESIZE: 10
      FILENAME: dump.pcap
      FILTER: "host opcplc"
volumes:
  dump:
