services:
  ############################
  # OPC PLC Simulation
  ############################
  opcplc:
    command: [
      "--sph=True",
      "--spf=/shared/pn.json",
      "--pn=50000",
      "--fn=8000",
      "--aa=True",
      "--ut=True"
      ]
  ############################
  # Network capture
  ############################
  pcap:
    container_name: pcap
    image: travelping/pcap
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - shared:/data:rw
    environment:
      IFACE: any
      FORMAT: pcapng
      MAXFILENUM: 10
      MAXFILESIZE: 200
      FILENAME: dump.pcap
      FILTER: "src or dst host 192.168.80.2"
volumes:
  shared:
