version: "3.9"
services:
  ############################
  # OPC PLC Simulation
  ############################
  # opcplc:
  #  environment:
  #   DOTNET_DiagnosticPorts: /shared/diag/dotnet-monitor.sock
  ############################
  # OPC Publisher
  ############################
  publisher:
    environment:
      DOTNET_DiagnosticPorts: /shared/diag/dotnet-monitor.sock
  ############################
  # dotnet-monitor
  ############################
  monitor:
    container_name: monitor
    image: mcr.microsoft.com/dotnet/monitor:latest
    ports:
      - "9084:52325"
    command: [ "collect", "--no-auth" ]
    environment:
      DOTNETMONITOR_DiagnosticPort__ConnectionMode: listen
      DOTNETMONITOR_Storage__DefaultSharedPath: /shared/diag
      DOTNETMONITOR_Storage__DumpTempFolder: /shared/diag/tmp
      DOTNETMONITOR_Metrics__Endpoints: http://+:52325
      DOTNETMONITOR_Urls: http://localhost:52323
    volumes:
      - shared:/shared
