apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: e2etesting
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: verifier
        image: registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/registry.password"
        volumeMounts:
        - name: registry-auth-config
          mountPath: /auth
      volumes:
        - name: registry-auth-config
          configMap:
            name: registry-auth-config