image: mcr.microsoft.com/iot/opc-ua-test-server
tag: 2.9.15-preview4
pullPolicy: Always
pullSecrets: []
# Controls number of OPC UA Test servers that should be deployed.
simulations: 1

# Unused, opc test always uses the default application certificate.
# TODO, remove and pass same to opc-plc as additionalArgs
autoAcceptUntrustedCertificates: true
# Controls if the security context should be set for the OPC UA Test server simulation server.
setSecurityContext: true
# Additional arguments for the OPC UA Test server simulation
# This should be an array of arrays, where each inner array contains the arguments for a specific instance.
additionalArgs: []

resources:
  requests:
    memory: 192Mi
    cpu: 125m
  limits:
    memory: 768Mi
    cpu: 500m

nameOverride: null
deployDefaultIssuerCA: false

