//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.IoTSolutions.Browser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.IoTSolutions.Browser.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action has executed....
        /// </summary>
        public static string ActionDetailResultExecuting {
            get {
                return ResourceManager.GetString("ActionDetailResultExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Instructions for Windows can be found &lt;a target=&quot;_blank&quot; style=&quot;text-decoration:underline&quot; href=&quot;https://go.microsoft.com/fwlink/p/?linkid=846367&quot;&gt;here&lt;/a&gt;.&lt;/div&gt;
        ///&lt;div&gt;Instructions for Linux be found &lt;a target=&quot;_blank&quot; style=&quot;text-decoration:underline&quot; href=&quot;https://go.microsoft.com/fwlink/p/?linkid=846368&quot;&gt;here&lt;/a&gt;.&lt;/div&gt; &lt;div&gt;Instructions for editing assembly line information can be found &lt;a target=&quot;_blank&quot; style=&quot;text-decoration:underline&quot; href=&quot;https://go.microsoft.com/fwlink/p/?linkid=846688&quot;&gt;here [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AddGatewayBodyPoint1 {
            get {
                return ResourceManager.GetString("AddGatewayBodyPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your own gateway.
        /// </summary>
        public static string AddGatewayTitle {
            get {
                return ResourceManager.GetString("AddGatewayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string AdministratorRole {
            get {
                return ResourceManager.GetString("AdministratorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge alert.
        /// </summary>
        public static string AlertActionAcknowledge {
            get {
                return ResourceManager.GetString("AlertActionAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert successfully acknowledged..
        /// </summary>
        public static string AlertActionAcknowledgeSuccessful {
            get {
                return ResourceManager.GetString("AlertActionAcknowledgeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close alert.
        /// </summary>
        public static string AlertActionClose {
            get {
                return ResourceManager.GetString("AlertActionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert successfully closed..
        /// </summary>
        public static string AlertActionCloseSuccessful {
            get {
                return ResourceManager.GetString("AlertActionCloseSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string AlertActionExecute {
            get {
                return ResourceManager.GetString("AlertActionExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check content in a new browser tab/window..
        /// </summary>
        public static string AlertActionWebPageOpened {
            get {
                return ResourceManager.GetString("AlertActionWebPageOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert cause.
        /// </summary>
        public static string AlertDescription {
            get {
                return ResourceManager.GetString("AlertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert details.
        /// </summary>
        public static string AlertDetails {
            get {
                return ResourceManager.GetString("AlertDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action result:.
        /// </summary>
        public static string AlertDetailsActionResultHeader {
            get {
                return ResourceManager.GetString("AlertDetailsActionResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string AlertDetailsDescriptionHeader {
            get {
                return ResourceManager.GetString("AlertDetailsDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string AlertDetailsLocationHeader {
            get {
                return ResourceManager.GetString("AlertDetailsLocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Action defined.
        /// </summary>
        public static string AlertDetailsNoActionAvailable {
            get {
                return ResourceManager.GetString("AlertDetailsNoActionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurences:.
        /// </summary>
        public static string AlertDetailsOccurencesHeader {
            get {
                return ResourceManager.GetString("AlertDetailsOccurencesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click chart to explore in Azure Time Series Insights.
        /// </summary>
        public static string AlertDetailsRdxLinkHeader {
            get {
                return ResourceManager.GetString("AlertDetailsRdxLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string AlertDetailsTimeHeader {
            get {
                return ResourceManager.GetString("AlertDetailsTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string AlertDetailsUnknown {
            get {
                return ResourceManager.GetString("AlertDetailsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alert information is no longer available..
        /// </summary>
        public static string AlertIdUnknown {
            get {
                return ResourceManager.GetString("AlertIdUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of products above maximum.
        /// </summary>
        public static string AlertKpi1AboveMaximum {
            get {
                return ResourceManager.GetString("AlertKpi1AboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of products below minimum.
        /// </summary>
        public static string AlertKpi1BelowMinimum {
            get {
                return ResourceManager.GetString("AlertKpi1BelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy consumption above maximum.
        /// </summary>
        public static string AlertKpi2AboveMaximum {
            get {
                return ResourceManager.GetString("AlertKpi2AboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy consumption below minimum.
        /// </summary>
        public static string AlertKpi2BelowMinimum {
            get {
                return ResourceManager.GetString("AlertKpi2BelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        public static string AlertNode {
            get {
                return ResourceManager.GetString("AlertNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Availability above maximum.
        /// </summary>
        public static string AlertOeeAvailabilityAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeeAvailabilityAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Availability below minimum.
        /// </summary>
        public static string AlertOeeAvailabilityBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeeAvailabilityBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Overall above maximum.
        /// </summary>
        public static string AlertOeeOverallAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeeOverallAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Overall below minimum.
        /// </summary>
        public static string AlertOeeOverallBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeeOverallBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Performance above maximum.
        /// </summary>
        public static string AlertOeePerformanceAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeePerformanceAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Performance below minimum.
        /// </summary>
        public static string AlertOeePerformanceBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeePerformanceBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Quality above maximum.
        /// </summary>
        public static string AlertOeeQualityAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeeQualityAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Qualty below minimum.
        /// </summary>
        public static string AlertOeeQualityBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeeQualityBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production line.
        /// </summary>
        public static string AlertProductionLine {
            get {
                return ResourceManager.GetString("AlertProductionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        public static string AlertsContainerHeader {
            get {
                return ResourceManager.GetString("AlertsContainerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action:.
        /// </summary>
        public static string AlertSelectAction {
            get {
                return ResourceManager.GetString("AlertSelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string AlertStation {
            get {
                return ResourceManager.GetString("AlertStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value above maximum.
        /// </summary>
        public static string AlertValueAboveMaximum {
            get {
                return ResourceManager.GetString("AlertValueAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value below minimum.
        /// </summary>
        public static string AlertValueBelowMinimum {
            get {
                return ResourceManager.GetString("AlertValueBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data from Azure Time Series Insights.
        /// </summary>
        public static string AnimationTimeSeriesLoading {
            get {
                return ResourceManager.GetString("AnimationTimeSeriesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing certificate for download.
        /// </summary>
        public static string BrowserCertDownloadError {
            get {
                return ResourceManager.GetString("BrowserCertDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection status:.
        /// </summary>
        public static string BrowserCommunicationStatusMessageLabel {
            get {
                return ResourceManager.GetString("BrowserCommunicationStatusMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string BrowserConnect {
            get {
                return ResourceManager.GetString("BrowserConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to OPC server.
        /// </summary>
        public static string BrowserConnectedTo {
            get {
                return ResourceManager.GetString("BrowserConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while connecting to the OPC UA server.
        /// </summary>
        public static string BrowserConnectErrorHeader {
            get {
                return ResourceManager.GetString("BrowserConnectErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to connect to the OPC UA server.
        ///Exceptionmessage:
        ///{0}
        ///Inner Message:
        ///{1}
        ///Stack trace:
        ///{2}.
        /// </summary>
        public static string BrowserConnectException {
            get {
                return ResourceManager.GetString("BrowserConnectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string BrowserConnecting {
            get {
                return ResourceManager.GetString("BrowserConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string BrowserContextPanelHeaderAttributes {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method call.
        /// </summary>
        public static string BrowserContextPanelHeaderMethod {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string BrowserContextPanelHeaderPublish {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read variable.
        /// </summary>
        public static string BrowserContextPanelHeaderRead {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish.
        /// </summary>
        public static string BrowserContextPanelHeaderUnpublish {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderUnpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write variable.
        /// </summary>
        public static string BrowserContextPanelHeaderWrite {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing....
        /// </summary>
        public static string BrowserContextPanelPublishing {
            get {
                return ResourceManager.GetString("BrowserContextPanelPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublishing....
        /// </summary>
        public static string BrowserContextPanelUnPublishing {
            get {
                return ResourceManager.GetString("BrowserContextPanelUnPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string BrowserDisconnectButton {
            get {
                return ResourceManager.GetString("BrowserDisconnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disconnect to the OPC UA server.
        ///Exceptionmessage:
        ///{0}
        ///Inner Message:
        ///{1}
        ///Stack trace:
        ///{2}.
        /// </summary>
        public static string BrowserDisconnectException {
            get {
                return ResourceManager.GetString("BrowserDisconnectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BrowserDontTrustButton {
            get {
                return ResourceManager.GetString("BrowserDontTrustButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download certificate.
        /// </summary>
        public static string BrowserDownload {
            get {
                return ResourceManager.GetString("BrowserDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should your OPC UA server require a manual installation of client certificates, you can download this website&apos;s OPC UA certificate here:.
        /// </summary>
        public static string BrowserDownloadText {
            get {
                return ResourceManager.GetString("BrowserDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you have connected your gateway, you can start connecting your own OPC UA servers. Enter your OPC UA server&apos;s endpoint URL (opc.tcp://servername.domain:portnumber) here:.
        /// </summary>
        public static string BrowserEnterOwn {
            get {
                return ResourceManager.GetString("BrowserEnterOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser error:.
        /// </summary>
        public static string BrowserError {
            get {
                return ResourceManager.GetString("BrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string BrowserErrorContinueButton {
            get {
                return ResourceManager.GetString("BrowserErrorContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message:.
        /// </summary>
        public static string BrowserErrorMessage {
            get {
                return ResourceManager.GetString("BrowserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string BrowserErrorServer {
            get {
                return ResourceManager.GetString("BrowserErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during browsing..
        /// </summary>
        public static string BrowserErrorUnknown {
            get {
                return ResourceManager.GetString("BrowserErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string BrowserOpcAttributesAny {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDimension.
        /// </summary>
        public static string BrowserOpcAttributesOneDimension {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesOneDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneOrMoreDimensions.
        /// </summary>
        public static string BrowserOpcAttributesOneOrMoreDimensions {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesOneOrMoreDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar.
        /// </summary>
        public static string BrowserOpcAttributesScalar {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesScalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScalarOrOneDimension.
        /// </summary>
        public static string BrowserOpcAttributesScalarOrOneDimension {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesScalarOrOneDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoDimensions.
        /// </summary>
        public static string BrowserOpcAttributesTwoDimensions {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesTwoDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic info.
        /// </summary>
        public static string BrowserOpcDataDiagnosticInfoLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataDiagnosticInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server timestamp.
        /// </summary>
        public static string BrowserOpcDataServerTimestampLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataServerTimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source timestamp.
        /// </summary>
        public static string BrowserOpcDataSourceTimestampLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataSourceTimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string BrowserOpcDataStatusLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string BrowserOpcDataValueLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while accessing the OPC UA server.
        /// </summary>
        public static string BrowserOpcErrorHeader {
            get {
                return ResourceManager.GetString("BrowserOpcErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while trying to access the OPC UA server.
        ///Exceptionmessage:
        ///{0}
        ///Inner message:
        ///{1}
        ///Stack trace:
        ///{2}.
        /// </summary>
        public static string BrowserOpcException {
            get {
                return ResourceManager.GetString("BrowserOpcException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method call failed.
        /// </summary>
        public static string BrowserOpcMethodCallFailed {
            get {
                return ResourceManager.GetString("BrowserOpcMethodCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method call succeeded.
        /// </summary>
        public static string BrowserOpcMethodCallSucceeded {
            get {
                return ResourceManager.GetString("BrowserOpcMethodCallSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method call succeeded and returned the following results:.
        /// </summary>
        public static string BrowserOpcMethodCallSucceededWithResults {
            get {
                return ResourceManager.GetString("BrowserOpcMethodCallSucceededWithResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code.
        /// </summary>
        public static string BrowserOpcMethodStatusCode {
            get {
                return ResourceManager.GetString("BrowserOpcMethodStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        public static string BrowserOpcValueContinuous {
            get {
                return ResourceManager.GetString("BrowserOpcValueContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string BrowserOpcValueHistory {
            get {
                return ResourceManager.GetString("BrowserOpcValueHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Update.
        /// </summary>
        public static string BrowserOpcValueHistoryUpdate {
            get {
                return ResourceManager.GetString("BrowserOpcValueHistoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminate.
        /// </summary>
        public static string BrowserOpcValueIndeterminate {
            get {
                return ResourceManager.GetString("BrowserOpcValueIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access.
        /// </summary>
        public static string BrowserOpcValueNoAccess {
            get {
                return ResourceManager.GetString("BrowserOpcValueNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readable.
        /// </summary>
        public static string BrowserOpcValueReadable {
            get {
                return ResourceManager.GetString("BrowserOpcValueReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string BrowserOpcValueSubscribe {
            get {
                return ResourceManager.GetString("BrowserOpcValueSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string BrowserOpcValueUnknown {
            get {
                return ResourceManager.GetString("BrowserOpcValueUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writeable.
        /// </summary>
        public static string BrowserOpcValueWriteable {
            get {
                return ResourceManager.GetString("BrowserOpcValueWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font color=&quot;red&quot;&gt;Error: Conversion of the value &apos;{0}&apos; to type &apos;{1}&apos; is not possible. (Details: {2})&lt;/font&gt;.
        /// </summary>
        public static string BrowserOpcWriteConversionProblem {
            get {
                return ResourceManager.GetString("BrowserOpcWriteConversionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a server from the preconfigured list:.
        /// </summary>
        public static string BrowserPreconfiguredListLabel {
            get {
                return ResourceManager.GetString("BrowserPreconfiguredListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string BrowserRootNodeName {
            get {
                return ResourceManager.GetString("BrowserRootNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Warning.
        /// </summary>
        public static string BrowserSecurityWarning {
            get {
                return ResourceManager.GetString("BrowserSecurityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your own OPC UA server.
        /// </summary>
        public static string BrowserSelectNewServer {
            get {
                return ResourceManager.GetString("BrowserSelectNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an OPC UA server.
        /// </summary>
        public static string BrowserSelectServer {
            get {
                return ResourceManager.GetString("BrowserSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This might mean that someone&apos;s trying to fool you or steal information you send to the server. You should proceed only if you expected this issue, e.g. because you are using self-signed certificates with your server (not recommended)..
        /// </summary>
        public static string BrowserTrust {
            get {
                return ResourceManager.GetString("BrowserTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string BrowserTrustButton {
            get {
                return ResourceManager.GetString("BrowserTrustButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate of the server you want to connect to cannot be verified..
        /// </summary>
        public static string BrowserTrustHeader {
            get {
                return ResourceManager.GetString("BrowserTrustHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should only proceed if you are sure you wish to make this change..
        /// </summary>
        public static string BrowserWriteWarning {
            get {
                return ResourceManager.GetString("BrowserWriteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will alter how your production line is configured..
        /// </summary>
        public static string BrowserWriteWarningHeader {
            get {
                return ResourceManager.GetString("BrowserWriteWarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Locations.
        /// </summary>
        public static string ChildrenFactoryListContainerHeaderPostfix {
            get {
                return ResourceManager.GetString("ChildrenFactoryListContainerHeaderPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT PRODUCTION.
        /// </summary>
        public static string ChildrenFactoryListListHeaderDetails {
            get {
                return ResourceManager.GetString("ChildrenFactoryListListHeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        public static string ChildrenFactoryListListHeaderLocation {
            get {
                return ResourceManager.GetString("ChildrenFactoryListListHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string ChildrenFactoryListListHeaderStatus {
            get {
                return ResourceManager.GetString("ChildrenFactoryListListHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string ChildrenOpcUaNodeListContainerHeaderPostfix {
            get {
                return ResourceManager.GetString("ChildrenOpcUaNodeListContainerHeaderPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALUE.
        /// </summary>
        public static string ChildrenOpcUaNodeListListHeaderDetails {
            get {
                return ResourceManager.GetString("ChildrenOpcUaNodeListListHeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string ChildrenOpcUaNodeListListHeaderLocation {
            get {
                return ResourceManager.GetString("ChildrenOpcUaNodeListListHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string ChildrenOpcUaNodeListListHeaderStatus {
            get {
                return ResourceManager.GetString("ChildrenOpcUaNodeListListHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string ChildrenProductionLineListContainerHeaderPostfix {
            get {
                return ResourceManager.GetString("ChildrenProductionLineListContainerHeaderPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT CONFIGURATION.
        /// </summary>
        public static string ChildrenProductionLineListListHeaderDetails {
            get {
                return ResourceManager.GetString("ChildrenProductionLineListListHeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINE.
        /// </summary>
        public static string ChildrenProductionLineListListHeaderLocation {
            get {
                return ResourceManager.GetString("ChildrenProductionLineListListHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string ChildrenProductionLineListListHeaderStatus {
            get {
                return ResourceManager.GetString("ChildrenProductionLineListListHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string ChildrenStationListContainerHeaderPostfix {
            get {
                return ResourceManager.GetString("ChildrenStationListContainerHeaderPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT CONFIGURATION.
        /// </summary>
        public static string ChildrenStationListListHeaderDetails {
            get {
                return ResourceManager.GetString("ChildrenStationListListHeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATION.
        /// </summary>
        public static string ChildrenStationListListHeaderLocation {
            get {
                return ResourceManager.GetString("ChildrenStationListListHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string ChildrenStationListListHeaderStatus {
            get {
                return ResourceManager.GetString("ChildrenStationListListHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected factory.
        /// </summary>
        public static string DefaultSolutionName {
            get {
                return ResourceManager.GetString("DefaultSolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while accessing the website..
        /// </summary>
        public static string ErrorAccessProblem {
            get {
                return ResourceManager.GetString("ErrorAccessProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid node or station.
        /// </summary>
        public static string ErrorGetDataForOpcUaNode {
            get {
                return ResourceManager.GetString("ErrorGetDataForOpcUaNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid node.
        /// </summary>
        public static string ErrorGetOeeKpiData {
            get {
                return ResourceManager.GetString("ErrorGetOeeKpiData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have insufficient permissions for this operation. Please check with the administrator of this site..
        /// </summary>
        public static string ErrorInsufficientPermissions {
            get {
                return ResourceManager.GetString("ErrorInsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string FilterApply {
            get {
                return ResourceManager.GetString("FilterApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string GraphFriday {
            get {
                return ResourceManager.GetString("GraphFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST 24 HOURS.
        /// </summary>
        public static string GraphLastDay {
            get {
                return ResourceManager.GetString("GraphLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST HOUR.
        /// </summary>
        public static string GraphLastHour {
            get {
                return ResourceManager.GetString("GraphLastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST 7 DAYS.
        /// </summary>
        public static string GraphLastWeek {
            get {
                return ResourceManager.GetString("GraphLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Threshold.
        /// </summary>
        public static string GraphMaxThreshold {
            get {
                return ResourceManager.GetString("GraphMaxThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Threshold.
        /// </summary>
        public static string GraphMinThreshold {
            get {
                return ResourceManager.GetString("GraphMinThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string GraphMonday {
            get {
                return ResourceManager.GetString("GraphMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on graph to explore in Azure Time Series Insights.
        /// </summary>
        public static string GraphRDXLinkHeader {
            get {
                return ResourceManager.GetString("GraphRDXLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        public static string GraphSaturday {
            get {
                return ResourceManager.GetString("GraphSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        public static string GraphSunday {
            get {
                return ResourceManager.GetString("GraphSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        public static string GraphThursday {
            get {
                return ResourceManager.GetString("GraphThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string GraphTuesday {
            get {
                return ResourceManager.GetString("GraphTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string GraphWednesday {
            get {
                return ResourceManager.GetString("GraphWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implicit Read-Only.
        /// </summary>
        public static string ImplicitReadOnlyRole {
            get {
                return ResourceManager.GetString("ImplicitReadOnlyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://azure.microsoft.com/solutions/iot-suite/.
        /// </summary>
        public static string InfoIconLink {
            get {
                return ResourceManager.GetString("InfoIconLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Suite.
        /// </summary>
        public static string IoTSuite {
            get {
                return ResourceManager.GetString("IoTSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units per hour.
        /// </summary>
        public static string Kpi1Label {
            get {
                return ResourceManager.GetString("Kpi1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kWh per hour.
        /// </summary>
        public static string Kpi2Label {
            get {
                return ResourceManager.GetString("Kpi2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Performance Indicators.
        /// </summary>
        public static string KpiContainerLabel {
            get {
                return ResourceManager.GetString("KpiContainerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string KpiMaximum {
            get {
                return ResourceManager.GetString("KpiMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string KpiMinimum {
            get {
                return ResourceManager.GetString("KpiMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string KpiTarget {
            get {
                return ResourceManager.GetString("KpiTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day (hours).
        /// </summary>
        public static string LastDayHistoryGraphXlabel {
            get {
                return ResourceManager.GetString("LastDayHistoryGraphXlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last hour (minutes).
        /// </summary>
        public static string LastHourHistoryGraphXlabel {
            get {
                return ResourceManager.GetString("LastHourHistoryGraphXlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week (days).
        /// </summary>
        public static string LastWeekHistoryGraphXlabel {
            get {
                return ResourceManager.GetString("LastWeekHistoryGraphXlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        public static string LinkLabelHelpAndSupport {
            get {
                return ResourceManager.GetString("LinkLabelHelpAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give feedback.
        /// </summary>
        public static string LinkLabelHelpGiveFeedback {
            get {
                return ResourceManager.GetString("LinkLabelHelpGiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure IoT Suite.
        /// </summary>
        public static string MicrosoftAzureIoTSuite {
            get {
                return ResourceManager.GetString("MicrosoftAzureIoTSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Gateway.
        /// </summary>
        public static string NavigationMenuAddGateway {
            get {
                return ResourceManager.GetString("NavigationMenuAddGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add my OPC Server.
        /// </summary>
        public static string NavigationMenuAddServer {
            get {
                return ResourceManager.GetString("NavigationMenuAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string NavigationMenuBrowser {
            get {
                return ResourceManager.GetString("NavigationMenuBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavigationMenuDashboard {
            get {
                return ResourceManager.GetString("NavigationMenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string NavigationMenuItemActions {
            get {
                return ResourceManager.GetString("NavigationMenuItemActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Menu Size.
        /// </summary>
        public static string NavigationMenuSidebarSizeToggle {
            get {
                return ResourceManager.GetString("NavigationMenuSidebarSizeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Factory.
        /// </summary>
        public static string NewFactoryName {
            get {
                return ResourceManager.GetString("NewFactoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Production Line.
        /// </summary>
        public static string NewProductionLineName {
            get {
                return ResourceManager.GetString("NewProductionLineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Station.
        /// </summary>
        public static string NewStationName {
            get {
                return ResourceManager.GetString("NewStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data series available for this item.
        /// </summary>
        public static string NoDataSeries {
            get {
                return ResourceManager.GetString("NoDataSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute of.
        /// </summary>
        public static string NodeAttribute {
            get {
                return ResourceManager.GetString("NodeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes....
        /// </summary>
        public static string NodeAttributeRead {
            get {
                return ResourceManager.GetString("NodeAttributeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string NodeButtonCall {
            get {
                return ResourceManager.GetString("NodeButtonCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string NodeButtonWrite {
            get {
                return ResourceManager.GetString("NodeButtonWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call....
        /// </summary>
        public static string NodeCall {
            get {
                return ResourceManager.GetString("NodeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling method.
        /// </summary>
        public static string NodeCallingMethod {
            get {
                return ResourceManager.GetString("NodeCallingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call in progress ....
        /// </summary>
        public static string NodeCallInProgress {
            get {
                return ResourceManager.GetString("NodeCallInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info on.
        /// </summary>
        public static string NodeInfo {
            get {
                return ResourceManager.GetString("NodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access:.
        /// </summary>
        public static string NodeLabelAccess {
            get {
                return ResourceManager.GetString("NodeLabelAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string NodeLabelDescription {
            get {
                return ResourceManager.GetString("NodeLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous:.
        /// </summary>
        public static string NodeLabelMisc {
            get {
                return ResourceManager.GetString("NodeLabelMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node details:.
        /// </summary>
        public static string NodeLabelNodeDetails {
            get {
                return ResourceManager.GetString("NodeLabelNodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string NodeLabelType {
            get {
                return ResourceManager.GetString("NodeLabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string NodeLabelValue {
            get {
                return ResourceManager.GetString("NodeLabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter are not supported yet..
        /// </summary>
        public static string NodeMethodMessage {
            get {
                return ResourceManager.GetString("NodeMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodName.
        /// </summary>
        public static string NodeMethodName {
            get {
                return ResourceManager.GetString("NodeMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method has no parameter..
        /// </summary>
        public static string NodeMethodNoParameter {
            get {
                return ResourceManager.GetString("NodeMethodNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of calling method.
        /// </summary>
        public static string NodeMethodResult {
            get {
                return ResourceManager.GetString("NodeMethodResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press button to call method..
        /// </summary>
        public static string NodePressButton {
            get {
                return ResourceManager.GetString("NodePressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish....
        /// </summary>
        public static string NodePublish {
            get {
                return ResourceManager.GetString("NodePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish in progress....
        /// </summary>
        public static string NodePublishInProgress {
            get {
                return ResourceManager.GetString("NodePublishInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read....
        /// </summary>
        public static string NodeRead {
            get {
                return ResourceManager.GetString("NodeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read in progress ....
        /// </summary>
        public static string NodeReadInProgress {
            get {
                return ResourceManager.GetString("NodeReadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish....
        /// </summary>
        public static string NodeUnpublish {
            get {
                return ResourceManager.GetString("NodeUnpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish in progress....
        /// </summary>
        public static string NodeUnpublishInProgress {
            get {
                return ResourceManager.GetString("NodeUnpublishInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string NodeUpdate {
            get {
                return ResourceManager.GetString("NodeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VariableName.
        /// </summary>
        public static string NodeVariableName {
            get {
                return ResourceManager.GetString("NodeVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write....
        /// </summary>
        public static string NodeWrite {
            get {
                return ResourceManager.GetString("NodeWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value:.
        /// </summary>
        public static string NodeWriteCurrentValue {
            get {
                return ResourceManager.GetString("NodeWriteCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write in progress ....
        /// </summary>
        public static string NodeWriteInProgress {
            get {
                return ResourceManager.GetString("NodeWriteInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value:.
        /// </summary>
        public static string NodeWriteNewValue {
            get {
                return ResourceManager.GetString("NodeWriteNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of writing.
        /// </summary>
        public static string NodeWriteResult {
            get {
                return ResourceManager.GetString("NodeWriteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string NoFilterApplied {
            get {
                return ResourceManager.GetString("NoFilterApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Required.
        /// </summary>
        public static string NoJScriptHeader {
            get {
                return ResourceManager.GetString("NoJScriptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser is currently set to block JavaScript. You need to allow JavaScript to use this service..
        /// </summary>
        public static string NoJScriptInfo1 {
            get {
                return ResourceManager.GetString("NoJScriptInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To learn how to allow JavaScript or to find out whether your browser supports JavaScript, check the online help in your web browser..
        /// </summary>
        public static string NoJScriptInfo2 {
            get {
                return ResourceManager.GetString("NoJScriptInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string OeeAvailabilityLabel {
            get {
                return ResourceManager.GetString("OeeAvailabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Equipment Efficiency.
        /// </summary>
        public static string OeeHeaderLabel {
            get {
                return ResourceManager.GetString("OeeHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Efficiency.
        /// </summary>
        public static string OeeOverallLabel {
            get {
                return ResourceManager.GetString("OeeOverallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string OeePerformanceLabel {
            get {
                return ResourceManager.GetString("OeePerformanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string OeeQualityLabel {
            get {
                return ResourceManager.GetString("OeeQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while initializing OPC UA stack. Error: {0} Inner: {1} Stack: {2}.
        /// </summary>
        public static string OpcStackInitError {
            get {
                return ResourceManager.GetString("OpcStackInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only.
        /// </summary>
        public static string ReadOnlyRole {
            get {
                return ResourceManager.GetString("ReadOnlyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not establish connection to Publisher.
        /// </summary>
        public static string SessionNull {
            get {
                return ResourceManager.GetString("SessionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect gateway.
        /// </summary>
        public static string TitleAddGateway {
            get {
                return ResourceManager.GetString("TitleAddGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect OPC UA server.
        /// </summary>
        public static string TitleAddOpcServer {
            get {
                return ResourceManager.GetString("TitleAddOpcServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string TitleBrowser {
            get {
                return ResourceManager.GetString("TitleBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string TitleDashboard {
            get {
                return ResourceManager.GetString("TitleDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in Time Series Insights.
        /// </summary>
        public static string Tsilink {
            get {
                return ResourceManager.GetString("Tsilink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UntrustedCertificate.
        /// </summary>
        public static string UntrustedCertificate {
            get {
                return ResourceManager.GetString("UntrustedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be signed in to continue..
        /// </summary>
        public static string YouMustBeSignedIn {
            get {
                return ResourceManager.GetString("YouMustBeSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you were signed in, your session has expired..
        /// </summary>
        public static string YourSessionMayHaveExpired {
            get {
                return ResourceManager.GetString("YourSessionMayHaveExpired", resourceCulture);
            }
        }
    }
}
