apiVersion: v1
entries:
  azure-industrial-iot:
  - apiVersion: v2
    appVersion: 2.8.4
    created: "2022-12-19T15:12:08.7090284+01:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: e8a2cab6e3b9f9bb2a415a25bea33fdf078c29d1ca3cec09589a4cb0f7a10555
    home: https://github.com/Azure/Industrial-IoT
    icon: https://raw.githubusercontent.com/Azure/Industrial-IoT/main/docs/media/microsoft-symbol.png
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.4.4.tgz
    version: 0.4.4
  - apiVersion: v2
    appVersion: 2.8.3
    created: "2022-06-15T16:04:22.8912842+02:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: 17e71996c8ac43b6c51d5a65b8569e9511896d4de9097e835fa7ffb2487ac6ed
    home: https://github.com/Azure/Industrial-IoT
    icon: https://raw.githubusercontent.com/Azure/Industrial-IoT/main/docs/media/microsoft-symbol.png
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.4.3.tgz
    version: 0.4.3
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-03-24T12:23:32.0120291+01:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: ccfeb419fd624c4793d7f5be63820be2278d21458708e49323600a1fa889f3d2
    home: https://github.com/Azure/Industrial-IoT
    icon: https://raw.githubusercontent.com/Azure/Industrial-IoT/main/docs/media/microsoft-symbol.png
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.4.2.tgz
    version: 0.4.2
  - apiVersion: v2
    appVersion: 2.8.1
    created: "2021-11-05T19:36:00.3656864+01:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: ec939fed989837f52b6eb5b12484bc45bb89a6a7d4bd389819bc97ad86b79bf0
    home: https://github.com/Azure/Industrial-IoT
    icon: https://raw.githubusercontent.com/Azure/Industrial-IoT/main/docs/media/microsoft-symbol.png
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 2.8.0
    created: "2021-09-02T18:49:54.1783583+02:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: c35d35a69c40743967dbde9ee5b6eff46a657d8cbed938b8837c776d92fcbd4b
    home: https://github.com/Azure/Industrial-IoT
    icon: https://raw.githubusercontent.com/Azure/Industrial-IoT/main/docs/media/microsoft-symbol.png
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 2.7.206
    created: "2021-01-28T11:55:28.75209+01:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: 57945361bf835f7e3a9f937307c02826cdf37da21ca580095095f68d784ca8fd
    home: https://github.com/Azure/Industrial-IoT
    icon: https://raw.githubusercontent.com/Azure/Industrial-IoT/master/docs/media/microsoft-symbol.png
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v2
    appVersion: 2.7.170
    created: "2020-07-08T11:44:50.2085401+02:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: cd309b00b3d16c093f706bf6f94eb0594bbbf3218a42954b408de23240bb75b9
    home: https://github.com/Azure/Industrial-IoT
    icon: https://raw.githubusercontent.com/Azure/Industrial-IoT/master/docs/media/microsoft-symbol.png
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: 2.7.105
    created: "2020-06-03T18:23:45.0627212+02:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: c857ae1df27aeaad6e332ec643996b6600a3ef5ac8ff21c77e2ace96453ea03e
    home: https://github.com/Azure/Industrial-IoT
    icon: https://raw.githubusercontent.com/Azure/Industrial-IoT/master/docs/media/microsoft-symbol.png
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 2.6.104
    created: "2020-03-23T11:44:42.2615071+01:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: 714ef5a376c323e3ef4048e3062b983fb5f64fe4b9aefbba1429f961e572ebff
    home: https://github.com/Azure/Industrial-IoT
    icon: https://github.com/Azure/Industrial-IoT/blob/master/docs/media/microsoft-symbol.png
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 2.5.2
    created: "2020-03-23T11:44:42.258476+01:00"
    description: Azure Industrial IoT allows plant operators to discover OPC UA enabled
      servers in a factory network and register them in Azure IoT Hub.
    digest: 6367e02f33a284842b2bd95e1b0504380dc6f23af26e5e2d26ebab8b65cdbee5
    home: https://github.com/Azure/Industrial-IoT
    keywords:
    - azure
    - iot
    - iiot
    - industrial-iot
    - azure-industrial-iot
    - opc-ua
    maintainers:
    - email: kakostan@microsoft.com
      name: Karapet Kostandyan
    name: azure-industrial-iot
    type: application
    urls:
    - https://azure.github.io/Industrial-IoT/helm/azure-industrial-iot-0.1.0.tgz
    version: 0.1.0
generated: "2022-12-19T15:12:08.7040284+01:00"
