//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.IIoT.Deployment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IIoTDeploymentTags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IIoTDeploymentTags() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.IIoT.Deployment.Resources.IIoTDeploymentTags", typeof(IIoTDeploymentTags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application.
        /// </summary>
        internal static string KEY_APPLICATION {
            get {
                return ResourceManager.GetString("KEY_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IotSuiteType.
        /// </summary>
        internal static string KEY_IOT_SUITE_TYPE {
            get {
                return ResourceManager.GetString("KEY_IOT_SUITE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to managed_by.
        /// </summary>
        internal static string KEY_MANAGED_BY {
            get {
                return ResourceManager.GetString("KEY_MANAGED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owner.
        /// </summary>
        internal static string KEY_OWNER {
            get {
                return ResourceManager.GetString("KEY_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string KEY_VERSION {
            get {
                return ResourceManager.GetString("KEY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureIndustrialIoT.
        /// </summary>
        internal static string VALUE_APPLICATION_IIOT {
            get {
                return ResourceManager.GetString("VALUE_APPLICATION_IIOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAI.
        /// </summary>
        internal static string VALUE_IOT_SUITE_TYPE_SUF {
            get {
                return ResourceManager.GetString("VALUE_IOT_SUITE_TYPE_SUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Azure.IIoT.Deployment.
        /// </summary>
        internal static string VALUE_MANAGED_BY_IIOT {
            get {
                return ResourceManager.GetString("VALUE_MANAGED_BY_IIOT", resourceCulture);
            }
        }
    }
}
