version: '3'
services:
  opcserver0:
    image: ${REPOSITORY:-mcr.microsoft.com}/iot/opc-ua-test-server:${VERSION:-latest}
    restart: always
    ports:
      - "51200:51200"
    environment:
      - SERVER_PORT=51200
  opcserver1:
    image: ${REPOSITORY:-mcr.microsoft.com}/iot/opc-ua-test-server:${VERSION:-latest}
    restart: always
    ports:
      - "51201:51201"
    environment:
      - SERVER_PORT=51201
  opcserver2:
    image: ${REPOSITORY:-mcr.microsoft.com}/iot/opc-ua-test-server:${VERSION:-latest}
    restart: always
    ports:
      - "51202:51202"
    environment:
      - SERVER_PORT=51202
