// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IIoT.OpcUa.Api.Vault.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CertificateRequestQueryResponseApiModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CertificateRequestQueryResponseApiModel class.
        /// </summary>
        public CertificateRequestQueryResponseApiModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CertificateRequestQueryResponseApiModel class.
        /// </summary>
        /// <param name="requests">The query result.</param>
        /// <param name="nextPageLink">Link to the next page of
        /// results.</param>
        public CertificateRequestQueryResponseApiModel(IList<CertificateRequestRecordApiModel> requests = default(IList<CertificateRequestRecordApiModel>), string nextPageLink = default(string))
        {
            Requests = requests;
            NextPageLink = nextPageLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the query result.
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<CertificateRequestRecordApiModel> Requests { get; set; }

        /// <summary>
        /// Gets or sets link to the next page of results.
        /// </summary>
        [JsonProperty(PropertyName = "nextPageLink")]
        public string NextPageLink { get; set; }

    }
}
