// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IIoT.OpcUa.Api.Vault.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class QueryApplicationsApiModel
    {
        /// <summary>
        /// Initializes a new instance of the QueryApplicationsApiModel class.
        /// </summary>
        public QueryApplicationsApiModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryApplicationsApiModel class.
        /// </summary>
        /// <param name="applicationType">Possible values include: 'any',
        /// 'server', 'client', 'clientAndServer'</param>
        /// <param name="applicationState">Possible values include: 'any',
        /// 'new', 'approved', 'rejected', 'unregistered', 'deleted'</param>
        public QueryApplicationsApiModel(string applicationName = default(string), string applicationUri = default(string), QueryApplicationType? applicationType = default(QueryApplicationType?), string productUri = default(string), IList<string> serverCapabilities = default(IList<string>), QueryApplicationState? applicationState = default(QueryApplicationState?))
        {
            ApplicationName = applicationName;
            ApplicationUri = applicationUri;
            ApplicationType = applicationType;
            ProductUri = productUri;
            ServerCapabilities = serverCapabilities;
            ApplicationState = applicationState;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationName")]
        public string ApplicationName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationUri")]
        public string ApplicationUri { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'any', 'server', 'client',
        /// 'clientAndServer'
        /// </summary>
        [JsonProperty(PropertyName = "applicationType")]
        public QueryApplicationType? ApplicationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productUri")]
        public string ProductUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serverCapabilities")]
        public IList<string> ServerCapabilities { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'any', 'new', 'approved',
        /// 'rejected', 'unregistered', 'deleted'
        /// </summary>
        [JsonProperty(PropertyName = "applicationState")]
        public QueryApplicationState? ApplicationState { get; set; }

    }
}
