apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: industrial-iot-role
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: industrial-iot
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.6.146
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
