apiVersion: v1
kind: Service
metadata:
  name: twin-service
  namespace: industrial-iot
  labels:
    app: twinservice
spec:
  type: ClusterIP
  selector:
    app: twinservice
  ports:
  - port: 443
    protocol: TCP
    name: https
  - port: 9041
    protocol: TCP
    name: rest
