apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alerting-deployment
  namespace: industrial-iot
  labels:
    app: alertingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertingservice
  template:
    metadata:
      labels:
        app: alertingservice
    spec:
      containers:
      - name: alertingservice
        image: mcr.microsoft.com/iot/opc-alerting-service:2.5.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: PCS_KEYVAULT_URL
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_KEYVAULT_URL
        - name: PCS_WORKSPACE_NAME
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_WORKSPACE_NAME
        - name: PCS_IOTHUB_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_IOTHUB_CONNSTRING
        - name: PCS_SERVICEBUS_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_SERVICEBUS_CONNSTRING
        - name: PCS_APPINSIGHTS_NAME
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_APPINSIGHTS_NAME
        - name: PCS_APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: industrial-iot-env
              key: PCS_APPINSIGHTS_INSTRUMENTATIONKEY
