apiVersion: v1
kind: Secret
metadata:
  name: industrial-iot-env
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: industrial-iot
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.5.2
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
type: Opaque
data:
  ####################----------2.6.104----------####################
  # IoT Hub
  PCS_IOTHUB_CONNSTRING: null
  PCS_IOTHUB_EVENTHUBENDPOINT: null
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_EVENTS: null
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_TELEMETRY: null
  # Cosmos DB
  PCS_COSMOSDB_CONNSTRING: null
  # Storage Account
  PCS_STORAGE_CONNSTRING: null
  PCS_STORAGE_CONTAINER_DATAPROTECTION: null
  # ADLS Gen2 Storage Account
  PCS_ADLSG2_CONNSTRING: null
  PCS_ADLSG2_CONTAINER_CDM: null
  PCS_ADLSG2_CONTAINER_CDM_ROOTFOLDER: null
  # Event Hub Namespace
  PCS_EVENTHUB_CONNSTRING: null
  PCS_EVENTHUB_NAME: null
  PCS_EVENTHUB_CONSUMERGROUP_TELEMETRY_CDM: null
  PCS_EVENTHUB_CONSUMERGROUP_TELEMETRY_UX: null
  # Service Bus
  PCS_SERVICEBUS_CONNSTRING: null
  # Key Vault
  PCS_KEYVAULT_URL: null
  PCS_KEYVAULT_KEY_DATAPROTECTION: null
  PCS_KEYVAULT_APPID: null
  PCS_KEYVAULT_SECRET: null
  # Application Insights
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: null
  # Service URLs
  PCS_SERVICE_URL: null
  PCS_TWIN_REGISTRY_URL: null
  PCS_TWIN_SERVICE_URL: null
  PCS_HISTORY_SERVICE_URL: null
  PCS_VAULT_SERVICE_URL: null
  PCS_ONBOARDING_SERVICE_URL: null
  PCS_PUBLISHER_SERVICE_URL: null
  PCS_JOBS_SERVICE_URL: null
  PCS_JOB_ORCHESTRATOR_SERVICE_URL: null
  PCS_CONFIGURATION_SERVICE_URL: null
  # SignalR
  PCS_SIGNALR_CONNSTRING: null
  # Authentication
  PCS_AUTH_TENANT: null
  PCS_AUTH_INSTANCE: null
  PCS_AUTH_ISSUER: null
  PCS_AUTH_HTTPSREDIRECTPORT: null
  PCS_AUTH_REQUIRED: null
  PCS_AUTH_AUDIENCE: null
  PCS_AUTH_CLIENT_APPID: null
  PCS_AUTH_CLIENT_SECRET: null
  PCS_AUTH_SERVICE_APPID: null
  PCS_AUTH_SERVICE_SECRET: null
  # CORS Whitelist
  PCS_CORS_WHITELIST: null
  # Service URL path bases
  PCS_TWIN_REGISTRY_SERVICE_PATH_BASE: null
  PCS_TWIN_SERVICE_PATH_BASE: null
  PCS_HISTORY_SERVICE_PATH_BASE: null
  PCS_GATEWAY_SERVICE_PATH_BASE: null
  PCS_VAULT_SERVICE_PATH_BASE: null
  PCS_ONBOARDING_SERVICE_PATH_BASE: null
  PCS_PUBLISHER_SERVICE_PATH_BASE: null
  PCS_CONFIGURATION_SERVICE_PATH_BASE: null
  PCS_EDGE_MANAGER_SERVICE_PATH_BASE: null
  PCS_FRONTEND_APP_SERVICE_PATH_BASE: null
  PCS_JOB_ORCHESTRATOR_SERVICE_PATH_BASE: null
  PCS_JOBS_SERVICE_PATH_BASE: null
  # AspNetCore
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: null
  ASPNETCORE_FORWARDEDHEADERS_FORWARDLIMIT: null
  # OpenAPI
  PCS_OPENAPI_SERVER_HOST: null
  ####################----------2.5.2----------####################
  _HUB_CS: null
  PCS_IOTHUB_CONNSTRING: null
  PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING: null
  PCS_TELEMETRY_DOCUMENTDB_CONNSTRING: null
  PCS_TELEMETRYAGENT_DOCUMENTDB_CONNSTRING: null
  PCS_IOTHUBREACT_ACCESS_CONNSTRING: null
  PCS_IOTHUBREACT_HUB_NAME: null
  PCS_IOTHUBREACT_HUB_ENDPOINT: null
  PCS_IOTHUBREACT_HUB_CONSUMERGROUP: null
  PCS_IOTHUBREACT_HUB_PARTITIONS: null
  PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT: null
  PCS_IOTHUBREACT_AZUREBLOB_KEY: null
  PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX: null
  PCS_ASA_DATA_AZUREBLOB_ACCOUNT: null
  PCS_ASA_DATA_AZUREBLOB_KEY: null
  PCS_ASA_DATA_AZUREBLOB_ENDPOINT_SUFFIX: null
  # PCS_EVENTHUB_CONNSTRING: null
  # PCS_EVENTHUB_NAME: null
  # PCS_SERVICEBUS_CONNSTRING: null
  # PCS_KEYVAULT_URL: null
  PCS_WORKSPACE_NAME: null
  PCS_APPINSIGHTS_NAME: null
  # PCS_APPINSIGHTS_INSTRUMENTATIONKEY: null
  # PCS_SERVICE_URL: null
  # PCS_SIGNALR_CONNSTRING: null
  # PCS_AUTH_HTTPSREDIRECTPORT: null
  # PCS_AUTH_REQUIRED: null
  # PCS_AUTH_AUDIENCE: null
  # PCS_AUTH_ISSUER: null
  PCS_WEBUI_AUTH_AAD_APPID: null
  PCS_WEBUI_AUTH_AAD_AUTHORITY: null
  PCS_WEBUI_AUTH_AAD_TENANT: null
  # PCS_CORS_WHITELIST: null
  REACT_APP_PCS_AUTH_REQUIRED: null
  REACT_APP_PCS_AUTH_AUDIENCE: null
  REACT_APP_PCS_AUTH_ISSUER: null
  REACT_APP_PCS_WEBUI_AUTH_AAD_APPID: null
  REACT_APP_PCS_WEBUI_AUTH_AAD_AUTHORITY: null
  REACT_APP_PCS_WEBUI_AUTH_AAD_TENANT: null
