apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: industrial-iot
  labels:
    app: historyservice
    app.kubernetes.io/name: historyservice
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.5.1
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
spec:
  type: ClusterIP
  selector:
    app: historyservice
  ports:
  - port: 443
    protocol: TCP
    name: https
  - port: 9043
    protocol: TCP
    name: rest
