apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-notification-deployment
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: blob-notification-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.5.2
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blob-notification-service
      app.kubernetes.io/part-of: industrial-iot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blob-notification-service
        app.kubernetes.io/part-of: industrial-iot
        app.kubernetes.io/version: 2.5.2
        app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
    spec:
      serviceAccountName: industrial-iot-serviceaccount
      containers:
      - name: blob-notification-service-container
        image: mcr.microsoft.com/iot/blob-notification-service:2.5.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        envFrom:
        - secretRef:
            name: industrial-iot-env
