apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: registry-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.5.2
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: registry-service
      app.kubernetes.io/part-of: industrial-iot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry-service
        app.kubernetes.io/part-of: industrial-iot
        app.kubernetes.io/version: 2.5.2
        app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: 9042
    spec:
      serviceAccountName: industrial-iot-serviceaccount
      containers:
      - name: registry-service-container
        image: mcr.microsoft.com/iot/opc-registry-service:2.5.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 443
        - containerPort: 9042
        envFrom:
        - secretRef:
            name: industrial-iot-env
