apiVersion: v1
kind: Service
metadata:
  name: twin-service
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: twin-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.6.146
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
    app.kubernetes.io/component: opc-twin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: twin-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/component: opc-twin
  ports:
  - port: 443
    protocol: TCP
    name: https
  - port: 9041
    protocol: TCP
    name: rest
