apiVersion: v1
kind: Service
metadata:
  name: onboarding-service
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: onboarding-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.6.146
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
    app.kubernetes.io/component: opc-onboarding-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: onboarding-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/component: opc-onboarding-service
  ports:
  - port: 9060
    targetPort: 9060
    protocol: TCP
    name: http
