apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-notification-deployment
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: blob-notification-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.6.146
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
    app.kubernetes.io/component: blob-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blob-notification-service
      app.kubernetes.io/part-of: industrial-iot
      app.kubernetes.io/component: blob-notification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blob-notification-service
        app.kubernetes.io/part-of: industrial-iot
        app.kubernetes.io/version: 2.6.146
        app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
        app.kubernetes.io/component: blob-notification
    spec:
      serviceAccountName: industrial-iot-serviceaccount
      containers:
      - name: blob-notification-service-container
        image: mcr.microsoft.com/iot/industrial-iot-fileupload-forwarder:2.6.146
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "384Mi"
            cpu: "150m"
        envFrom:
        - secretRef:
            name: industrial-iot-env
