apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-deployment
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: publisher-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.6.146
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
    app.kubernetes.io/component: opc-publisher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: publisher-service
      app.kubernetes.io/part-of: industrial-iot
      app.kubernetes.io/component: opc-publisher-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: publisher-service
        app.kubernetes.io/part-of: industrial-iot
        app.kubernetes.io/version: 2.6.146
        app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
        app.kubernetes.io/component: opc-publisher-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: 9045
    spec:
      serviceAccountName: industrial-iot-serviceaccount
      containers:
      - name: publisher-service-container
        image: mcr.microsoft.com/iot/opc-publisher-service:2.6.146
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "384Mi"
            cpu: "150m"
        ports:
        - containerPort: 9045
        envFrom:
        - secretRef:
            name: industrial-iot-env
