apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: configuration-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.6.146
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
    app.kubernetes.io/component: industrial-iot-configuration-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: configuration-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/component: industrial-iot-configuration-service
  ports:
  - port: 9050
    targetPort: 9050
    protocol: TCP
    name: http
