apiVersion: v1
kind: Service
metadata:
  name: engineering-tool-service
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: engineering-tool-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.6.146
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
    app.kubernetes.io/component: industrial-iot-engineering-tool
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: engineering-tool-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/component: industrial-iot-engineering-tool
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
