apiVersion: apps/v1
kind: Deployment
metadata:
  name: engineering-tool-deployment
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: engineering-tool-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.6.146
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
    app.kubernetes.io/component: industrial-iot-engineering-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: engineering-tool-service
      app.kubernetes.io/part-of: industrial-iot
      app.kubernetes.io/component: industrial-iot-engineering-tool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: engineering-tool-service
        app.kubernetes.io/part-of: industrial-iot
        app.kubernetes.io/version: 2.6.146
        app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
        app.kubernetes.io/component: industrial-iot-engineering-tool
      # annotations:
      #   prometheus.io/scrape: 'true'
      #   prometheus.io/port: 80
    spec:
      serviceAccountName: industrial-iot-serviceaccount
      containers:
      - name: engineering-tool-service-container
        image: mcr.microsoft.com/iot/industrial-iot-frontend:2.6.146
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "384Mi"
            cpu: "150m"
        ports:
        - containerPort: 80
        - containerPort: 443
        envFrom:
        - secretRef:
            name: industrial-iot-env
