apiVersion: v1
kind: Service
metadata:
  name: edge-jobs-service
  namespace: industrial-iot
  labels:
    app.kubernetes.io/name: edge-jobs-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/version: 2.6.146
    app.kubernetes.io/managed-by: Microsoft.Azure.IIoT.Deployment
    app.kubernetes.io/component: industrial-iot-jobs-orchestrator-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: edge-jobs-service
    app.kubernetes.io/part-of: industrial-iot
    app.kubernetes.io/component: industrial-iot-jobs-orchestrator-service
  ports:
  - port: 9051
    targetPort: 9051
    protocol: TCP
    name: http
