// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
//  Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
// ------------------------------------------------------------

namespace Microsoft.Azure.IIoT.OpcUa.Registry.Tests.Deploy {
    using Autofac;
    using Autofac.Extras.Moq;
    using Microsoft.Azure.IIoT.Deploy.Runtime;
    using Microsoft.Azure.IIoT.Hub;
    using Microsoft.Azure.IIoT.Hub.Models;
    using Microsoft.Azure.IIoT.OpcUa.Registry.Deploy;
    using Microsoft.Azure.IIoT.Serializers;
    using Microsoft.Azure.IIoT.Serializers.NewtonSoft;
    using Microsoft.Extensions.Configuration;
    using Moq;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Xunit;

    /// <summary>
    /// Test to check layered deployments that are generated by IoTHubMetricsCollectorDeployment
    /// </summary>
    public class IoTHubMetricsCollectorDeploymentTests {

        [Fact]
        public async Task MetricsCollectorDeploymentRoutesTestAsync() {

            IList<ConfigurationModel> configurationModelList = new List<ConfigurationModel>();

            var ioTHubConfigurationServicesMock = new Mock<IIoTHubConfigurationServices>();
            ioTHubConfigurationServicesMock
                .Setup(e => e.CreateOrUpdateConfigurationAsync(It.IsAny<ConfigurationModel>(), true, CancellationToken.None))
                .Callback<ConfigurationModel, bool, CancellationToken>(
                    (confModel, forceUpdate, ct) => configurationModelList.Add(confModel))
                .Returns((ConfigurationModel configuration, bool forceUpdate, CancellationToken ct) => Task.FromResult(configuration));

            var configuration = new ConfigurationBuilder()
                .AddInMemoryCollection()
                .Build();
            configuration["Docker:WorkspaceId"] = "WorkspaceId";
            configuration["Docker:WorkspaceKey"] = "WorkspaceKey";
            configuration["SubscriptionId"] = "SubscriptionId";
            configuration["ResourceGroupName"] = "ResourceGroupName";
            configuration["IoTHubConnectionString"] = "HostName=test.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=test";

            using (var mock = Setup(ioTHubConfigurationServicesMock, configuration)) {
                var metricsCollectorDeploymentService = mock.Create<IoTHubMetricsCollectorDeployment>();
                await metricsCollectorDeploymentService.StartAsync();

                Assert.Equal(2, configurationModelList.Count);

                {
                    var configurationModel = configurationModelList[0];
                    Assert.Equal("__default-metricscollector-linux", configurationModel.Id);
                    Assert.Equal(2, configurationModel.Content.ModulesContent.Count);

                    // Check routes of layered deployment for Linux
                    Assert.Equal("FROM /messages/modules/metricscollector/* INTO $upstream",
                        configurationModel.Content.ModulesContent["$edgeHub"]["properties.desired.routes.metricscollectorToUpstream"]);

                    // Check docker image
                    var module = (Newtonsoft.Json.Linq.JObject)configurationModel.Content.ModulesContent["$edgeAgent"]["properties.desired.modules.metricscollector"];
                    Assert.Equal("mcr.microsoft.com/azureiotedge-metrics-collector:1.0",
                        module["settings"].Value<string>("image"));

                    // Check environment variables
                    Assert.Equal("AzureMonitor",
                        module["env"]["UploadTarget"].Value<string>("value"));
                    Assert.Equal("WorkspaceId",
                        module["env"]["LogAnalyticsWorkspaceId"].Value<string>("value"));
                    Assert.Equal("WorkspaceKey",
                        module["env"]["LogAnalyticsSharedKey"].Value<string>("value"));
                    Assert.Equal("/subscriptions/SubscriptionId/resourceGroups/ResourceGroupName/providers/Microsoft.Devices/IotHubs/test",
                        module["env"]["ResourceId"].Value<string>("value"));
                    Assert.Equal("http://edgehub:9600/metrics,http://edgeagent:9600/metrics,http://twin:9701/metrics,http://publisher:9702/metrics",
                        module["env"]["MetricsEndpointsCSV"].Value<string>("value"));
                }
                {
                    var configurationModel = configurationModelList[1];
                    Assert.Equal("__default-metricscollector-windows", configurationModel.Id);
                    Assert.Equal(2, configurationModel.Content.ModulesContent.Count);

                    // Check routes of layered deployment for Windows
                    Assert.Equal("FROM /messages/modules/metricscollector/* INTO $upstream",
                        configurationModel.Content.ModulesContent["$edgeHub"]["properties.desired.routes.metricscollectorToUpstream"]);

                    // Check docker image
                    var module = (Newtonsoft.Json.Linq.JObject)configurationModel.Content.ModulesContent["$edgeAgent"]["properties.desired.modules.metricscollector"];
                    Assert.Equal("mcr.microsoft.com/azureiotedge-metrics-collector:1.0",
                        module["settings"].Value<string>("image"));

                    // Check environment variables
                    Assert.Equal("AzureMonitor",
                        module["env"]["UploadTarget"].Value<string>("value"));
                    Assert.Equal("WorkspaceId",
                        module["env"]["LogAnalyticsWorkspaceId"].Value<string>("value"));
                    Assert.Equal("WorkspaceKey",
                        module["env"]["LogAnalyticsSharedKey"].Value<string>("value"));
                    Assert.Equal("/subscriptions/SubscriptionId/resourceGroups/ResourceGroupName/providers/Microsoft.Devices/IotHubs/test",
                        module["env"]["ResourceId"].Value<string>("value"));
                    Assert.Equal("http://edgehub:9600/metrics,http://edgeagent:9600/metrics,http://twin:9701/metrics,http://publisher:9702/metrics",
                        module["env"]["MetricsEndpointsCSV"].Value<string>("value"));
                }
            }
        }

        [Fact]
        public async Task EmptyIotHubResourceIdConfigTestAsync() {

            IList<ConfigurationModel> configurationModelList = new List<ConfigurationModel>();

            var ioTHubConfigurationServicesMock = new Mock<IIoTHubConfigurationServices>();
            ioTHubConfigurationServicesMock
                .Setup(e => e.CreateOrUpdateConfigurationAsync(It.IsAny<ConfigurationModel>(), true, CancellationToken.None))
                .Callback<ConfigurationModel, bool, CancellationToken>(
                    (confModel, forceUpdate, ct) => configurationModelList.Add(confModel))
                .Returns((ConfigurationModel configuration, bool forceUpdate, CancellationToken ct) => Task.FromResult(configuration));

            var configuration = new ConfigurationBuilder()
                .AddInMemoryCollection()
                .Build();
            configuration["Docker:WorkspaceId"] = "WorkspaceId";
            configuration["Docker:WorkspaceKey"] = "WorkspaceKey";
            configuration["SubscriptionId"] = "";
            configuration["ResourceGroupName"] = null;
            configuration["IoTHubConnectionString"] = "HostName=test.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=test";

            using (var mock = Setup(ioTHubConfigurationServicesMock, configuration)) {
                var metricsCollectorDeploymentService = mock.Create<IoTHubMetricsCollectorDeployment>();
                await metricsCollectorDeploymentService.StartAsync();
                Assert.Equal(0, configurationModelList.Count);
            }
        }

        [Fact]
        public async Task EmptyLogWorkspaceConfigTestAsync() {

            IList<ConfigurationModel> configurationModelList = new List<ConfigurationModel>();

            var ioTHubConfigurationServicesMock = new Mock<IIoTHubConfigurationServices>();
            ioTHubConfigurationServicesMock
                .Setup(e => e.CreateOrUpdateConfigurationAsync(It.IsAny<ConfigurationModel>(), true, CancellationToken.None))
                .Callback<ConfigurationModel, bool, CancellationToken>(
                    (confModel, forceUpdate, ct) => configurationModelList.Add(confModel))
                .Returns((ConfigurationModel configuration, bool forceUpdate, CancellationToken ct) => Task.FromResult(configuration));

            using (var mock = Setup(ioTHubConfigurationServicesMock)) {
                var metricsCollectorDeploymentService = mock.Create<IoTHubMetricsCollectorDeployment>();
                var jsonserializer = mock.Container.Resolve<IJsonSerializer>();

                await metricsCollectorDeploymentService.StartAsync();

                Assert.Equal(0, configurationModelList.Count);
            }
        }

        /// <summary>
        /// Setup mock
        /// </summary>
        /// <param name="ioTHubConfigurationServicesMock"></param>
        /// <param name="configuration"></param>
        private static AutoMock Setup(
            Mock<IIoTHubConfigurationServices> ioTHubConfigurationServicesMock = null,
            IConfiguration configuration = null
        ) {
            var mock = AutoMock.GetLoose(builder => {
                // Use empty configuration root if one is not passed.
                var conf = configuration ?? new ConfigurationBuilder()
                    .AddInMemoryCollection()
                    .Build();

                // Setup configuration
                builder.RegisterInstance(conf)
                    .As<IConfiguration>()
                    .SingleInstance();

                var logWorkspaceConfig = new LogWorkspaceConfig(conf);
                builder.RegisterInstance(logWorkspaceConfig)
                    .AsImplementedInterfaces()
                    .SingleInstance();

                // Setup JSON serializer
                builder.RegisterType<NewtonSoftJsonConverters>()
                    .As<IJsonSerializerConverterProvider>();
                builder.RegisterType<NewtonSoftJsonSerializer>()
                    .As<IJsonSerializer>();

                // Setup IIoTHubConfigurationServices mock
                if (ioTHubConfigurationServicesMock is null) {
                    var ioTHubConfigurationServices = new Mock<IIoTHubConfigurationServices>();
                    ioTHubConfigurationServices
                        .Setup(e => e.CreateOrUpdateConfigurationAsync(It.IsAny<ConfigurationModel>(), true, CancellationToken.None))
                        .Returns((ConfigurationModel configuration, bool forceUpdate, CancellationToken ct) => Task.FromResult(configuration));
                    builder.RegisterMock(ioTHubConfigurationServices);
                }
                else {
                    builder.RegisterMock(ioTHubConfigurationServicesMock);
                }

                builder.RegisterType<IoTHubMetricsCollectorDeployment>()
                    .AsSelf(); ;
            });
            return mock;
        }
    }
}
