version: '3'
services:
  opcserver0:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    restart: always
    command: --aa -pn 51200 -fn 50 -fr 1 -sn 250 -sr 10
    ports:
      - "51200:51200"
  opcserver1:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    restart: always
    command: --aa -pn 51200 -fn 50 -fr 1 -sn 250 -sr 10
    ports:
      - "51201:51201"
  opcserver2:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    restart: always
    command: --aa -pn 51200 -fn 50 -fr 1 -sn 250 -sr 10
    ports:
      - "51202:51202"
