#!/usr/bin/env bash -e

# Usage:
# Build the project in the local environment:  ./Scripts/build
# Build the project inside a Docker container: ./Scripts/build -s
# Build the project inside a Docker container: ./Scripts/build --in-sandbox

# Debug|Release
CONFIGURATION=Release

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/Scripts/.functions.sh"

# Folder where PCS sandboxes cache data. Reuse the same folder to speed up the
# sandbox and to save disk space.
# Use PCS_CACHE="$APP_HOME/.cache" to cache inside the project folder
PCS_CACHE="/tmp/azure/iotpcs/.cache"

compile() {
    check_dependency_dotnet

    cd $APP_HOME
    ./Scripts/env-vars-check

    header "Downloading dependencies..."
    dotnet restore

    header "Compiling code..."
    dotnet build --configuration $CONFIGURATION
}

run_tests() {
    check_dependency_dotnet

    cd $APP_HOME
    header "Running tests..."
    PROJECTS=$(dotnet sln list | grep 'csproj$' | grep '\.Test')
    for PROJ in $PROJECTS; do
        echo "-- $PROJ"
        dotnet test --configuration $CONFIGURATION $PROJ
    done
}

setup_sandbox_cache() {
    mkdir -p $PCS_CACHE/sandbox/.config
    mkdir -p $PCS_CACHE/sandbox/.dotnet
    mkdir -p $PCS_CACHE/sandbox/.nuget
    echo "Note: caching build files in $PCS_CACHE"
}

build_in_sandbox() {

    setup_sandbox_cache

    cd $APP_HOME

    # In Windows this script should use docker.exe, in which case
    # the parameters syntax is different, e.g. volumes path
    # (i.e. C:\path\path\... vs /c/path/path/...).
    #
    # Note that this script is also used for the git precommit hook.
    set +e
    IS_WINDOWS=$(which cmd.exe)
    set -e
    if [[ -z "$IS_WINDOWS" ]]; then
        check_dependency_docker
        docker run \
            -e "_HUB_CS=$_HUB_CS" \
            -e "_STORE_CS=$_STORE_CS" \
            -e "_EH_CS=$_EH_CS" \
            -v "$PCS_CACHE/sandbox/.config:/root/.config" \
            -v "$PCS_CACHE/sandbox/.dotnet:/root/.dotnet" \
            -v "$PCS_CACHE/sandbox/.nuget:/root/.nuget" \
            -v "$APP_HOME:/opt/code" \
            azureiotpcs/code-builder-dotnet:1.0-dotnetcore /opt/code/Scripts/build
    else
        # Note 'winpty' is required to provide a TTY to Docker
        echo "Launching cmd.exe /c winpty ..."
        cmd.exe /c "winpty .\Scripts\build.cmd --in-sandbox"
    fi
}

if [[ "$1" == "--in-sandbox" || "$1" == "-s" ]]; then
    build_in_sandbox
else
    # workaround for https://github.com/dotnet/cli/issues/3995
    unset home

    compile
    run_tests
fi

set +e
