apiVersion: v1
kind: ConfigMap
metadata:
  name: publisher-pn-config
  namespace: e2etesting
data:
  pn.json: |-
    [
      {
        "EndpointUrl": "opc.tcp://opcplc:50000",
        "UseSecurity": false,
        "OpcNodes": [
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=StepUp" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=AlternatingBoolean" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=RandomSignedInt32" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=RandomUnsignedInt32" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=65e451f1-56f1-ce84-a44f-6addf176beaf" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=DipData" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt1" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt2" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt3" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt4" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt5" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt6" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt7" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt8" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt9" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=FastUInt10" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=BadFastUInt1" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=NegativeTrendData" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=PositiveTrendData" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=SlowUInt1", "OpcPublishingInterval": 10000 },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=BadSlowUInt1", "OpcPublishingInterval": 10000 },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=SpikeData" },
          { "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=panic" }
        ]
      }
    ]