apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcpublisher
  namespace: e2etesting
spec:
  selector:
    matchLabels:
      app: opcpublisher
  template:
    metadata:
      labels:
        app: opcpublisher
    spec:
      containers:
      - name: opcpublisher
        image: {{ContainerRegistryServer}}/{{ImageNamespace}}iotedge/opc-publisher:{{ImageTag}}
        args: [
          "--mqc=HostName=mosquitto;Port=1883;DeviceId={{DeviceId}}",
          "--PkiRootPath=/mount/pki",   # Path to PKI folders
          "--pf=/config/pn.json",       # Path to Published Nodes file
          "--lf=/mount/publisher.log",  # Path to log file 
          "--mm=PubSub",                # Message Format OPC UA PubSub
          "--me=Json",                  # Message Encoding Json
          "--fd=false",                 # Deactivate Fetch Display Names
          "--bs=150",                   # BatchSize 150 incoming messages
          "--bi=1000",                  # Batch Interval 1s
          "--di=20",                    # Diagnostic Interval 20s
          "--aa"                        # Auto Accept OPC UA Server certificates
          ]
        volumeMounts:
        - name: opcpublisher-config
          mountPath: /config/pn.json
          subPath: pn.json
        - name: opcpublisher-volume
          mountPath: /mount
{{ImagePullSecret}}      imagePullSecrets:
{{ImagePullSecret}}        - name: dev-registry-pull-secret 
      volumes:
        - name: opcpublisher-volume
        - name: opcpublisher-config
          configMap:
            name: publisher-pn-config
