trigger: none

variables:
- template: steps/variables.yml
- name: ResourceGroupName
  value: publisher-mqtt-k8s
- name: Region
  value: northeurope
- name: Cleanup
  value: false
- name: PublisherImagePath
  value: mqtt-publisher
- name: ContainerRegistryServer
  value: edgeappmodel.azurecr.io
    

stages:
# build test resource
# upload test resource

- stage: deployAKS
  displayName: "Deploy AKS"
  jobs:
  - job: deployaks
    displayName: 'Deploy aks cluster'
    timeoutInMinutes: 30
    steps: 
    - template: steps/deployaks.yml

# run tests

- stage: testAKS
  displayName: Test 
  dependsOn: deployAKS
  condition: not(canceled())
  jobs:
  - job: debug
    variables:
      verifierIp:  $[ stageDependencies.deployAKS.deployaks.outputs['resolveverifierip.VerifierIp'] ]
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: Write-Host $(verifierIp)
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: Write-Host $[ stageDependencies.deployAKS.deployaks.outputs]
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: Write-Host $[ dependencies.deployAKS.outputs]
  - job: test
    displayName: Test
    steps:
    - template: steps/testaks.yml
      parameters:
        Verifier_Endpoint: $[ stageDependencies.deployAKS.deployaks.outputs['resolveverifierip.VerifierIp'] ]
        # Verifier_Endpoint: "http://$[stageDependencies.deployAKS.deployaks.outputs['resolveverifierip.VerifierIp']]):80"
        Broker_Endpoint: mosquitto
        Broker_Port: 1883
        Topic: "devices/#"
        Time_To_Observe: "5000" 


- stage: cleanup
  displayName: Cleanup resources
  dependsOn: testAKS
  condition: and(not(canceled()), eq(variables['Cleanup'], true))
  jobs:
  - job: cleanup
    displayName: Cleanup
    steps:
    - template: steps/cleanupaks.yml
      parameters:
        CleanupAppRegistrations: false