name: $(Date:yyyyMMdd)$(Rev:rr)

trigger: none
pr: none

pool:
  name: '$(AgentPool)'

variables:
- template: steps/variables.yml

stages:
- stage: build
  displayName: "Build Resources"
  condition: ne(variables['UseExisting'], true)
  jobs:
  - job: buildiai
    displayName: 'Build IAI'
    steps:
    - template: steps/buildiai.yml

  - job: buildtestresources
    displayName: 'Build Test Resources'
    steps:
    - template: steps/buildtestresources.yml

- stage: deploy
  displayName: "Deploy Components"
  dependsOn: build
  condition: eq(dependencies.build.result, 'Succeeded')
  jobs:  
  - job: deployplatform
    displayName: 'Deploy Platform'
    steps:
    - template: steps/deployplatform.yml

  - job: deploytestresources
    condition: eq(dependencies.deployplatform.result, 'Succeeded')
    dependsOn: deployplatform
    displayName: 'Deploy Test Resources'
    pool:
      name: '$(AgentPool)'
    steps:
    - template: steps/deploytestresources.yml

- stage: runtests
  displayName: "Execute tests"
  dependsOn: deploy
  condition: or(eq(dependencies.deploy.result, 'Succeeded'), eq(dependencies.deploy.result, 'Skipped'))
  jobs:
  - job: runtestspublisher
    timeoutInMinutes: 45
    displayName: 'Execute publisher tests'
    steps:
    - template: steps/runtests.yml
      parameters:
        ModeName: PublisherMode
        ModeValue: orchestrated
  - job: runteststwin
    timeoutInMinutes: 45
    displayName: 'Execute twin tests'
    steps:
    - template: steps/runtests.yml
      parameters:
        ModeName: TwinMode
        ModeValue: default
  - job: runtestsdiscovery
    timeoutInMinutes: 45
    displayName: 'Execute discovery tests'
    steps:
    - template: steps/runtests.yml
      parameters:
        ModeName: DiscoveryMode
        ModeValue: default

- stage: cleanup
  displayName: Cleanup resources
  dependsOn: runtests
  condition: and(not(canceled()), eq(variables['Cleanup'], true))
  jobs:
  - job: cleanup
    displayName: Cleanup
    steps:
    - template: steps/cleanup.yml
      parameters:
        CleanupAppRegistrations: true
  
