name: $(Date:yyyyMMdd)$(Rev:rr)

trigger: none
pr: none

schedules:
- cron: "0 10 * * *"
  displayName: Nightly build of main and release branch.
  branches:
    include:
    - main
    - release
    - releases
  always: true

# Trigger Orchestrated E2E Pipeline post completion of build pipeline.
resources:
  pipelines:
  - pipeline: Industrial-IoT-Official
    source: OneBranch\Industrial-IoT\Industrial-IoT-Official
    trigger:
      branches:
        include:
        - refs/heads/releases
        - refs/heads/release/*
        - refs/heads/main
  - pipeline: Industrial-IoT-Buddy
    source: OneBranch\Industrial-IoT\Industrial-IoT-Buddy
    trigger:
      branches:
        include:
        - '*' # All branches

pool:
  vmImage: 'windows-latest'

variables:
- template: steps/variables.yml

stages:
- stage: build
  displayName: "Build Resources"
  condition: ne(variables['UseExisting'], true)
  jobs:
  - job: buildtestresources
    displayName: 'Build Test Resources'
    steps:
    - template: steps/buildtestresources.yml

- stage: deploy
  displayName: "Deploy Components"
  dependsOn: build
  condition: and(not(canceled()), eq(dependencies.build.result, 'Succeeded'))
  jobs:
  - job: deploystandalone
    displayName: 'Deploy Standalone Resources'
    steps:
    - template: steps/deploystandalone.yml

  - job: deploytestresources
    condition: and(not(canceled()), eq(dependencies.deploystandalone.result, 'Succeeded'))
    dependsOn: deploystandalone
    displayName: 'Deploy Test Resources'
    steps:
    - template: steps/deploytestresources.yml

- stage: runtests
  displayName: "Execute tests"
  dependsOn: deploy
  condition: and(not(canceled()), or(eq(dependencies.deploy.result, 'Succeeded'), eq(dependencies.deploy.result, 'Skipped')))
  jobs:
  - job: runtestsae
    timeoutInMinutes: 150
    displayName: 'Run A&E End to End Tests'
    steps:
    - template: steps/runtests.yml
      parameters:
        ModeName: PublisherMode
        ModeValue: AE
  - job: runtestsbasic
    timeoutInMinutes: 150
    dependsOn: runtestsae
    displayName: 'Run Basic End to End Tests'
    steps:
    - template: steps/runtests.yml
      parameters:
        ModeName: PublisherMode
        ModeValue: standalone

- stage: cleanup
  displayName: Cleanup resources
  dependsOn: runtests
  condition: and(not(canceled()), eq(variables['Cleanup'], true))
  jobs:
  - job: cleanup
    displayName: Cleanup
    steps:
    - template: steps/cleanup.yml
      parameters:
        CleanupAppRegistrations: false
