name: $(Date:yyyyMMdd)$(Rev:rr)

trigger: none
pr: none

pool: 'Azure-IoT-Manufacturing'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host myVar value: "$(myVar)"'
