name: $(Date:yyyyMMdd)$(Rev:rr)

variables:
- name: 'BasePath'
  value: '$(System.DefaultWorkingDirectory)\tools\e2etesting'

jobs:
- job: A
  displayName: 'Job A'
  pool:
    name: 'Azure-IoT-Manufacturing'
  steps:
  - task: PowerShell@2
    name: outputstep
    displayName: "Write Output variable"
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: $(BasePath)\Test1.ps1

- job: B
  displayName: "Job B"
  variables:
  - name: MyVariableFromA
    value: $[ dependencies.A.outputs['outputstep.MyVariable'] ]
  dependsOn: A
  pool:
    name: 'Azure-IoT-Manufacturing'
  steps:
  - task: PowerShell@2
    displayName: "echo value"
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: $(BasePath)\Test2.ps1
      scriptArguments: >
        -Value "$(MyVariableFromA)"
  - script: echo $(MyVariableFromA)
