#
# Build images in acr
#
parameters:
  useNugets: 'False'
jobs:
- job: imagesprep
  displayName: Prepare Image Jobs
  pool:
    name: Hosted Windows 2019 with VS2019
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - task: PowerShell@2
    name: acrmatrix
    displayName: Prepare Builds
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/acr-matrix.ps1
- job: imagesall
  displayName: Build Images for
  pool:
    name: Hosted Windows 2019 with VS2019
  dependsOn: imagesprep
  strategy:
    matrix: $[ dependencies.imagesprep.outputs['acrmatrix.acrMatrix'] ]
  variables:
    skipComponentGovernanceDetection: true
    PROJECT_BUILD: ${{ parameters.useNugets }}
  steps:
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/set-version.ps1
  - task: AzureCLI@1
    name: acrbuildr
    displayName: Build Release Images
    inputs:
      azureSubscription: azureiiot
      scriptLocation: inlineScript
      inlineScript: powershell ./tools/scripts/acr-build.ps1 $(dockerFolder)
  - task: AzureCLI@1
    name: acrbuildd
    displayName: Build Debug Images
    inputs:
      azureSubscription: azureiiot
      scriptLocation: inlineScript
      inlineScript: powershell ./tools/scripts/acr-build.ps1 $(dockerFolder) -debug
      
