# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# The SBOM tasks have been removed because they are not required for the unofficial template.
# You can manually enable SBOM in the unofficial template if needed, othewise its automatically enabled when using official template. https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sbom
# The Task 'PublishPipelineArtifact@1' has been converted to an output named 'Publish Release Artifact' in the templateContext section.
# The Task 'PublishPipelineArtifact@1' has been converted to an output named 'Publish Debug Artifact' in the templateContext section.
jobs:
- job: buildprep
  displayName: Prepare Build Jobs
  variables:
    runCodesignValidationInjection: false
    skipComponentGovernanceDetection: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: PowerShell@2
    name: buildmatrix
    displayName: Prepare Solutions
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/get-matrix.ps1
      arguments: -FileName Industrial-IoT.sln
- job: buildall
  displayName: Building
  dependsOn: buildprep
  strategy:
    matrix: $[dependencies.buildprep.outputs['buildmatrix.jobMatrix'] ]
  variables:
    skipComponentGovernanceDetection: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    runCodesignValidationInjection: false
  templateContext:
    outputs:
    - output: pipelineArtifact
      displayName: 'Publish Release Artifact'
      targetPath: $(System.ArtifactsDirectory)/$(agent)_Release
      artifactName: $(agent)_Release
    - output: pipelineArtifact
      displayName: 'Publish Debug Artifact'
      targetPath: $(System.ArtifactsDirectory)/$(agent)_Debug
      artifactName: $(agent)_Debug
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: sdk
      version: 8.0.x
      includePreviewVersions: false
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/set-version.ps1
  - task: DotNetCoreCLI@2
    displayName: 'Build Release'
    inputs:
      command: build
      projects: '$(file)'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/$(agent)_Release'
  - task: DotNetCoreCLI@2
    displayName: 'Build Debug'
    inputs:
      command: build
      projects: '$(file)'
      arguments: '--configuration Debug --output $(Build.ArtifactStagingDirectory)/$(agent)_Debug'
- job: testprep
  displayName: Prepare Test Jobs
  variables:
    runCodesignValidationInjection: false
    skipComponentGovernanceDetection: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: PowerShell@2
    name: testmatrix
    displayName: Prepare Tests
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/get-matrix.ps1
      arguments: -FileName azure-pipelines.yml
- job: testall
  displayName: Run Tests for
  dependsOn: testprep
  strategy:
    matrix: $[dependencies.testprep.outputs['testmatrix.jobMatrix'] ]
  variables:
    skipComponentGovernanceDetection: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    runCodesignValidationInjection: false
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: sdk
      version: 8.0.x
      includePreviewVersions: false
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/set-version.ps1
  - task: DotNetCoreCLI@2
    displayName: Test
    timeoutInMinutes: 90
    inputs:
      command: test
      projects: '**/tests/*.csproj'
      arguments: '--blame-hang --blame-hang-timeout 10m --blame-hang-dump-type full --blame-crash --blame-crash-dump-type full --configuration Release'