# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
parameters:
  e2eOrchestratedPipelineId: 20
  e2eStandalonePipelineId: 21
  branchName: main
jobs:
- job: buildprep
  displayName: Triggering E2E tests
  pool: server
  steps:
  - task: InvokeRESTAPI@1
    displayName: 'Trigger Azure.Industrial-IoT-E2ETesting-Orchestrated'
    continueOnError: true
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: iotcat-Azure.Industrial-IoT-E2ETesting
      method: 'POST'
      urlSuffix: ${{ parameters.e2eOrchestratedPipelineId }}/runs?api-version=6.0-preview.1
      headers: '{ "Content-Type": "application/json" }'
      body: '{ "resources": { "repositories": { "self": { "refName": "${{ parameters.branchName }}" }}}}'
      waitForCompletion: 'false'
  - task: InvokeRESTAPI@1
    displayName: 'Trigger Azure.Industrial-IoT-E2ETesting-Standalone'
    continueOnError: true
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: iotcat-Azure.Industrial-IoT-E2ETesting
      method: 'POST'
      urlSuffix: ${{ parameters.e2eStandalonePipelineId }}/runs?api-version=6.0-preview.1
      headers: '{ "Content-Type": "application/json" }'
      body: '{ "resources": { "repositories": { "self": { "refName": "${{ parameters.branchName }}" }}}}'
      waitForCompletion: 'false'