jobs:
- job: buildprep
  displayName: Triggering E2E tests
  pool: server
#   pool:
#     vmImage: 'windows-2019'
#   variables:
#     secret: tbd
  steps:
  - task: InvokeRESTAPI@1
    displayName: 'Trigger Azure.Industrial-IoT-E2ETesting-Orchestrated'
    inputs:
      connectionType: 'connectedServiceName' # Options: connectedServiceName, connectedServiceNameARM
      serviceConnection: iotcat-Azure.Industrial-IoT-E2ETesting-Orchestrated # Required when connectionType == ConnectedServiceName
      method: 'POST'
      urlSuffix: /runs?api-version=6.0-preview.1
      headers: '{Content-Type:application/json}'
      body: '{ "resources": { "repositories": { "self": { "refName": "kakostan/iotcat" }}}}'
      waitForCompletion: 'false' # Options: true, false
      #successCriteria: # Optional