#
# Publish Microsoft.Azure.IIoT.Deployment Executables on Linux
#
parameters:
  runtime: linux-x64
  vmImage: ubuntu-latest

jobs:
- job: iiot_deployment_linux
  displayName: Generate Linux Executables
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: build_iiot_deployment.yml
    parameters:
      runtime: ${{ parameters.runtime }}
  - task: CmdLine@2
    displayName: 'Generate MD5 Checksum'
    inputs:
      script:  md5sum Microsoft.Azure.IIoT.Deployment Microsoft.Azure.IIoT.Deployment.pdb > Microsoft.Azure.IIoT.Deployment.md5
      workingDirectory: $(Build.ArtifactStagingDirectory)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Deployment
  - task: ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifacts'
    inputs:
      path: $(Build.ArtifactStagingDirectory)/
      artifact: iiot_deployment_release_$(setVersionInfo.Version_Prefix)$(setVersionInfo.Version_Prerelease)_${{ parameters.runtime }}
  - task: AzureCLI@2
    displayName: 'Copy to Blob'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
    inputs:
      azureSubscription: '$(iaiStorageAccountSubscription)'
      scriptType: pscore
      workingDirectory: $(Build.ArtifactStagingDirectory)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Deployment
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob upload --overwrite true --account-name $(iaiStorageAccount) --container-name binaries -f Microsoft.Azure.IIoT.Deployment     --name ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}/$(setVersionInfo.Version_Prefix)$(setVersionInfo.Version_Prerelease)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Deployment
        az storage blob upload --overwrite true --account-name $(iaiStorageAccount) --container-name binaries -f Microsoft.Azure.IIoT.Deployment.pdb --name ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}/$(setVersionInfo.Version_Prefix)$(setVersionInfo.Version_Prerelease)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Deployment.pdb
        az storage blob upload --overwrite true --account-name $(iaiStorageAccount) --container-name binaries -f Microsoft.Azure.IIoT.Deployment.md5 --name ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}/$(setVersionInfo.Version_Prefix)$(setVersionInfo.Version_Prerelease)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Deployment.md5
        az storage blob upload --overwrite true --account-name $(iaiStorageAccount) --container-name binaries -f Microsoft.Azure.IIoT.Deployment     --name ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}/preview/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Deployment
        az storage blob upload --overwrite true --account-name $(iaiStorageAccount) --container-name binaries -f Microsoft.Azure.IIoT.Deployment.pdb --name ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}/preview/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Deployment.pdb
        az storage blob upload --overwrite true --account-name $(iaiStorageAccount) --container-name binaries -f Microsoft.Azure.IIoT.Deployment.md5 --name ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}/preview/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Deployment.md5
