#
# Pack nugets for consumption
#
jobs:
- job: nuget
  displayName: Release Nugets
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/set-version.ps1
  - task: DownloadPipelineArtifacts@2
    inputs:
      artifact: 'release_nugets'
      path: $(Build.ArtifactStagingDirectory)
  - task: NuGetCommand@2
    displayName: 'NuGet Release Push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.snupkg'
      nuGetFeedType: external
      publishFeedCredentials: 'azureiiot-nuget'
      verbosityPush: Normal
    continueOnError: true
