#
# Build simulation environment - Linux
#
parameters:
  poolName: 'windows-2019'
  rgName: 'sandbox-iiot'
  deviceCount: '1'

jobs:
  - job: Build_linux_environment
    displayName: Build linux environment
    pool:
      vmImage: ${{ parameters.poolName }}
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: 'AzureRmPipeline-conn'
        subscriptionName: '9dd2b4d0-3dad-4aeb-85d8-c3addb78127a'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{ parameters.rgName }}-linux-rg'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'tools/templates/simulation_linux_iot.json'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'ARMOutputIOT'
    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'AzureRmPipeline-conn'
        ScriptType: 'FilePath'
        ScriptPath: 'tools/scripts/read-output-params.ps1'
        ScriptArguments: '-armOutputString ''$(ARMOutputIOT)'''
        azurePowerShellVersion: 'LatestVersion'
    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'AzureRmPipeline-conn'
        ScriptType: 'FilePath'
        ScriptPath: 'tools/scripts/create-edge.ps1'
        ScriptArguments: '-ResourceGroupName "$(Output_resourceGroup)" -IoTHubName "$(Output_iothub-name)" -IoTHubConnectionString "$(Output_iothub-connstring)" -Env "linux" -VmCount "${{ parameters.deviceCount }}"'
        azurePowerShellVersion: 'LatestVersion'
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: 'AzureRmPipeline-conn'
        subscriptionName: '9dd2b4d0-3dad-4aeb-85d8-c3addb78127a'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{ parameters.rgName }}-linux-rg'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'tools/templates/simulation_linux.json'
        overrideParameters: '-edgeUsername "sandboxuserlinux" -edgePassword $(vmPassword) -edgeDeviceKey $(Output_edgeKey) -deviceCount ${{ parameters.deviceCount }}'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'ARMOutput'
    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'AzureRmPipeline-conn'
        ScriptType: 'FilePath'
        ScriptPath: 'tools/scripts/read-output-params.ps1'
        ScriptArguments: '-armOutputString ''$(ARMOutput)'''
        azurePowerShellVersion: 'LatestVersion'
