apiVersion: v1
kind: ConfigMap
metadata:
  name: opcplc-config
  namespace: e2etesting
data:
  nodesfile.json: |-
    { 
      "Folder": "MyTelemetry",
      "NodeList": [
        {
          "NodeId": "panic",
          "Name": "Panic",
          "DataType": "Boolean",
          "ValueRank": -1,
          "AccessLevel": "CurrentReadOrWrite",
          "Description": "Node that panics, if written"
        }
      ]     
    }
  