name: $(Date:yyyyMMdd)$(Rev:rr)
trigger: none
pr: none

variables:
- template: steps/variables.yml

stages:
# build test resource
# upload test resource

- stage: deployAKS
  displayName: "Deploy AKS"
  jobs:
  - job: deployaks
    displayName: 'Deploy aks cluster'
    timeoutInMinutes: 30
    steps: 
    - template: steps/deployaks.yml

# run tests

- stage: testAKS
  displayName: Test 
  dependsOn: deployAKS
  jobs:
  - job: test
    displayName: Test
    variables:
      verifierIp:  $[ stageDependencies.deployAKS.deployaks.outputs['resolveverifierip.VerifierIp'] ]
    steps:
    - template: steps/testaks.yml
      parameters:
        Verifier_Endpoint: "http://$(verifierIp):80"
        Broker_Endpoint: mosquitto
        Broker_Port: 1883
        Topic: "devices/#"
        Time_To_Observe: "5000" 

- stage: cleanup
  displayName: Cleanup resources
  dependsOn: testAKS
  condition: and(not(canceled()), eq(variables['Cleanup'], true))
  jobs:
  - job: cleanup
    displayName: Cleanup
    steps:
    - template: steps/cleanupaks.yml
      parameters:
        CleanupAppRegistrations: false