apiVersion: v1
kind: Secret
metadata:
  name: {{ template "azure-industrial-iot.env.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: azure-industrial-iot-env
    app.kubernetes.io/part-of: azure-industrial-iot
type: Opaque
data:
{{- /* IoT Hub */}}
  PCS_IOTHUB_CONNSTRING: {{ required "A valid .Values.azure.iotHub.sharedAccessPolicies.iothubowner.connectionString is required!" .Values.azure.iotHub.sharedAccessPolicies.iothubowner.connectionString | b64enc }}
  PCS_IOTHUB_EVENTHUBENDPOINT: {{ required "A valid .Values.azure.iotHub.eventHub.endpoint is required!" .Values.azure.iotHub.eventHub.endpoint | b64enc }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup.events }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup.telemetry }}
  {{- if eq ( trim .Values.azure.iotHub.eventHub.consumerGroup.events ) ( trim .Values.azure.iotHub.eventHub.consumerGroup.telemetry ) }}
  {{- fail ".Values.azure.iotHub.eventHub.consumerGroup.events and .Values.azure.iotHub.eventHub.consumerGroup.telemetry should have different values!" }}
  {{- else }}
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_EVENTS: {{ required "A valid .Values.azure.iotHub.eventHub.consumerGroup.events is required!" .Values.azure.iotHub.eventHub.consumerGroup.events | b64enc }}
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_TELEMETRY: {{ required "A valid .Values.azure.iotHub.eventHub.consumerGroup.telemetry is required!" .Values.azure.iotHub.eventHub.consumerGroup.telemetry | b64enc }}
  {{- end }}
  {{- else }}
  {{- fail "A valid .Values.azure.iotHub.eventHub.consumerGroup.telemetry is required!" }}
  {{- end }}
  {{- else }}
  {{- fail "A valid .Values.azure.iotHub.eventHub.consumerGroup.events is required!" }}
  {{- end }}
  {{- else }}
  {{- fail "Valid .Values.azure.iotHub.eventHub.consumerGroup.events and .Values.azure.iotHub.eventHub.consumerGroup.telemetry are required!" }}
  {{- end }}
{{- /* Cosmos DB */}}
  PCS_COSMOSDB_CONNSTRING: {{ required "A valid .Values.azure.cosmosDB.connectionString is required!" .Values.azure.cosmosDB.connectionString | b64enc }}
{{- /* Storage Account */}}
  PCS_STORAGE_CONNSTRING: {{ required "A valid .Values.azure.storageAccount.connectionString is required!" .Values.azure.storageAccount.connectionString | b64enc }}
  {{- if .Values.azure.storageAccount.container }}
  {{- if .Values.azure.storageAccount.container.dataProtection }}
  PCS_STORAGE_CONTAINER_DATAPROTECTION: {{ .Values.azure.storageAccount.container.dataProtection | b64enc }}
  {{- else }}
  PCS_STORAGE_CONTAINER_DATAPROTECTION: ""
  {{- end }}
  {{- else }}
  PCS_STORAGE_CONTAINER_DATAPROTECTION: ""
  {{- end }}
{{- /* Event Hub Namespace and Event Hubs */}}
  PCS_EVENTHUB_CONNSTRING: {{ required "A valid .Values.azure.eventHubNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString is required!" .Values.azure.eventHubNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString | b64enc }}
  PCS_EVENTHUB_NAME: {{ required "A valid .Values.azure.eventHubNamespace.eventHub.name is required!" .Values.azure.eventHubNamespace.eventHub.name | b64enc }}
  {{- if .Values.azure.eventHubNamespace.eventHub.consumerGroup }}
  {{- if .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm }}
  {{- if .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx }}
  {{- if eq ( trim .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm ) ( trim .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx ) }}
  {{- fail ".Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm and .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx should have different values!" }}
  {{- else }}
  PCS_EVENTHUB_CONSUMERGROUP_TELEMETRY_CDM: {{ required "A valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm is required!" .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm | b64enc }}
  PCS_EVENTHUB_CONSUMERGROUP_TELEMETRY_UX: {{ required "A valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx is required!" .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx | b64enc }}
  {{- end }}
  {{- else }}
  {{- fail "A valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx is required!" }}
  {{- end }}
  {{- else }}
  {{- fail "A valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm is required!" }}
  {{- end }}
  {{- else }}
  {{- fail "Valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm and .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx are required!" }}
  {{- end }}
{{- /* Service Bus */}}
  PCS_SERVICEBUS_CONNSTRING: {{ required "A valid .Values.azure.serviceBusNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString is required!" .Values.azure.serviceBusNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString | b64enc }}
{{- /* Key Vault */}}
  PCS_KEYVAULT_URL: {{ required "A valid .Values.azure.keyVault.uri is required!" .Values.azure.keyVault.uri | b64enc }}
  {{- if .Values.azure.keyVault.key }}
  {{- if .Values.azure.keyVault.key.dataProtection }}
  PCS_KEYVAULT_KEY_DATAPROTECTION: {{ .Values.azure.keyVault.key.dataProtection | b64enc }}
  {{- else }}
  PCS_KEYVAULT_KEY_DATAPROTECTION: ""
  {{- end }}
  {{- else }}
  PCS_KEYVAULT_KEY_DATAPROTECTION: ""
  {{- end }}
  {{- if .Values.azure.auth.required }}
  PCS_KEYVAULT_APPID: {{ required "A valid .Values.azure.auth.servicesApp.appId is required!" .Values.azure.auth.servicesApp.appId | b64enc }}
  PCS_KEYVAULT_SECRET: {{ required "A valid .Values.azure.auth.servicesApp.secret is required!" .Values.azure.auth.servicesApp.secret | b64enc }}
  {{- else }}
  PCS_KEYVAULT_APPID: ""
  PCS_KEYVAULT_SECRET: ""
  {{- end }}
{{- /* Log Analytics Workspace */}}
  {{- if .Values.azure.logAnalyticsWorkspace }}
  {{- if .Values.azure.logAnalyticsWorkspace.name }}
  PCS_WORKSPACE_NAME: {{ .Values.azure.logAnalyticsWorkspace.name | b64enc }}
  {{- else }}
  PCS_WORKSPACE_NAME: ""
  {{- end }}
  {{- else }}
  PCS_WORKSPACE_NAME: ""
  {{- end }}
{{- /* Application Insights */}}
  {{- if .Values.azure.applicationInsights }}
  {{- if .Values.azure.applicationInsights.instrumentationKey }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.azure.applicationInsights.instrumentationKey | b64enc }}
  {{- else }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: ""
  {{- end }}
  {{- else }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: ""
  {{- end }}
{{- /* App Service */}}
  {{- if .Values.azure.appService }}
  {{- if .Values.azure.appService.url }}
  PCS_SERVICE_URL: {{ .Values.azure.appService.url | b64enc }}
  {{- else }}
  PCS_SERVICE_URL: ""
  {{- end }}
  {{- else }}
  PCS_SERVICE_URL: ""
  {{- end }}
  PCS_SIGNALR_CONNSTRING: {{ required "A valid .Values.azure.signalR.connectionString is required!" .Values.azure.signalR.connectionString | b64enc }}
{{- /* Authentication */}}
  PCS_AUTH_TENANT: {{ required "A valid .Values.azure.tenantId is required!" .Values.azure.tenantId | b64enc }}
  PCS_AUTH_INSTANCE: {{ required "A valid .Values.azure.auth.authority is required!" .Values.azure.auth.authority | b64enc }}
  PCS_AUTH_ISSUER: {{ required "A valid .Values.azure.tenantId is required!" .Values.azure.tenantId | printf "https://sts.windows.net/%s/" | b64enc }}
  PCS_AUTH_HTTPSREDIRECTPORT: {{ "0" | b64enc }}
  {{- if .Values.azure.auth.required }}
  PCS_AUTH_REQUIRED: {{ .Values.azure.auth.required | printf "%t" | b64enc }}
  PCS_AUTH_AUDIENCE: {{ required "A valid .Values.azure.auth.servicesApp.audience is required!" .Values.azure.auth.servicesApp.audience | b64enc }}
  PCS_AUTH_CLIENT_APPID: {{ required "A valid .Values.azure.auth.clientsApp.appId is required!" .Values.azure.auth.clientsApp.appId | b64enc }}
  PCS_AUTH_CLIENT_SECRET: {{ required "A valid .Values.azure.auth.clientsApp.secret is required!" .Values.azure.auth.clientsApp.secret | b64enc }}
  PCS_AUTH_SERVICE_APPID: {{ required "A valid .Values.azure.auth.servicesApp.appId is required!" .Values.azure.auth.servicesApp.appId | b64enc }}
  PCS_AUTH_SERVICE_SECRET: {{ required "A valid .Values.azure.auth.servicesApp.secret is required!" .Values.azure.auth.servicesApp.secret | b64enc }}
  {{- else }}
  PCS_AUTH_REQUIRED: {{ false | printf "%t" | b64enc }}
  PCS_AUTH_AUDIENCE: ""
  PCS_AUTH_CLIENT_APPID: ""
  PCS_AUTH_CLIENT_SECRET: ""
  PCS_AUTH_SERVICE_APPID: ""
  PCS_AUTH_SERVICE_SECRET: ""
  {{- end }}
{{- /* CORS Whitelist */}}
  PCS_CORS_WHITELIST: {{ required "A valid .Values.azure.auth.corsWhitelist is required!" .Values.azure.auth.corsWhitelist | b64enc }}
