apiVersion: v1
kind: Secret
metadata:
  name: {{ template "azure-industrial-iot.env.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: azure-industrial-iot-env
    app.kubernetes.io/part-of: azure-industrial-iot
type: Opaque
data:
  PCS_IOTHUB_CONNSTRING: {{ required "A valid .Values.azure.iotHub.sharedAccessPolicies.iothubowner.connectionString is required!" .Values.azure.iotHub.sharedAccessPolicies.iothubowner.connectionString | b64enc }}
  PCS_IOTHUB_EVENTHUBENDPOINT: {{ required "A valid .Values.azure.iotHub.eventHub.endpoint is required!" .Values.azure.iotHub.eventHub.endpoint | b64enc }}
  PCS_IOTHUB_EVENTHUBCONSUMERGROUP: {{ required "A valid .Values.azure.iotHub.eventHub.consumerGroup is required!" .Values.azure.iotHub.eventHub.consumerGroup | b64enc }}
  PCS_COSMOSDB_CONNSTRING: {{ required "A valid .Values.azure.cosmosDB.connectionString is required!" .Values.azure.cosmosDB.connectionString | b64enc }}
  PCS_STORAGE_CONNSTRING: {{ required "A valid .Values.azure.storageAccount.connectionString is required!" .Values.azure.storageAccount.connectionString | b64enc }}
  PCS_EVENTHUB_CONNSTRING: {{ required "A valid .Values.azure.eventHubNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString is required!" .Values.azure.eventHubNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString | b64enc }}
  {{- if .Values.azure.eventHubNamespace.eventHub }}
  {{- if .Values.azure.eventHubNamespace.eventHub.name }}
  PCS_EVENTHUB_NAME: {{ .Values.azure.eventHubNamespace.eventHub.name | b64enc }}
  {{- else }}
  PCS_EVENTHUB_NAME: ""
  {{- end }}
  {{- else }}
  PCS_EVENTHUB_NAME: ""
  {{- end }}
  PCS_SERVICEBUS_CONNSTRING: {{ required "A valid .Values.azure.serviceBusNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString is required!" .Values.azure.serviceBusNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString | b64enc }}
  PCS_KEYVAULT_URL: {{ required "A valid .Values.azure.keyVault.uri is required!" .Values.azure.keyVault.uri | b64enc }}
  {{- if .Values.azure.logAnalyticsWorkspace }}
  {{- if .Values.azure.logAnalyticsWorkspace.name }}
  PCS_WORKSPACE_NAME: {{ .Values.azure.logAnalyticsWorkspace.name | b64enc }}
  {{- else }}
  PCS_WORKSPACE_NAME: ""
  {{- end }}
  {{- else }}
  PCS_WORKSPACE_NAME: ""
  {{- end }}
  {{- if .Values.azure.applicationInsights }}
  {{- if .Values.azure.applicationInsights.instrumentationKey }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.azure.applicationInsights.instrumentationKey | b64enc }}
  {{- else }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: ""
  {{- end }}
  {{- else }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: ""
  {{- end }}
  {{- if .Values.azure.appService }}
  {{- if .Values.azure.appService.url }}
  PCS_SERVICE_URL: {{ .Values.azure.appService.url | b64enc }}
  {{- else }}
  PCS_SERVICE_URL: ""
  {{- end }}
  {{- else }}
  PCS_SERVICE_URL: ""
  {{- end }}
  PCS_SIGNALR_CONNSTRING: {{ required "A valid .Values.azure.signalR.connectionString is required!" .Values.azure.signalR.connectionString | b64enc }}
{{- /* Authentication */}}
  PCS_AUTH_TENANT: {{ required "A valid .Values.azure.tenantId is required!" .Values.azure.tenantId | b64enc }}
  PCS_AUTH_INSTANCE: {{ required "A valid .Values.azure.auth.authority is required!" .Values.azure.auth.authority | b64enc }}
  PCS_AUTH_ISSUER: {{ required "A valid .Values.azure.tenantId is required!" .Values.azure.tenantId | printf "https://sts.windows.net/%s/" | b64enc }}
  PCS_AUTH_HTTPSREDIRECTPORT: {{ "0" | b64enc }}
  {{- if .Values.azure.auth.required }}
  PCS_AUTH_REQUIRED: {{ .Values.azure.auth.required | printf "%t" | b64enc }}
  PCS_AUTH_AUDIENCE: {{ required "A valid .Values.azure.auth.servicesApp.audience is required!" .Values.azure.auth.servicesApp.audience | b64enc }}
  PCS_AUTH_CLIENT_APPID: {{ required "A valid .Values.azure.auth.clientsApp.appId is required!" .Values.azure.auth.clientsApp.appId | b64enc }}
  PCS_AUTH_SERVICE_APPID: ""
  {{- else }}
  PCS_AUTH_REQUIRED: {{ false | printf "%t" | b64enc }}
  PCS_AUTH_AUDIENCE: ""
  PCS_AUTH_CLIENT_APPID: ""
  PCS_AUTH_SERVICE_APPID: ""
  {{- end }}
{{- /* CORS Whitelist */}}
  PCS_CORS_WHITELIST: {{ required "A valid .Values.azure.auth.corsWhitelist is required!" .Values.azure.auth.corsWhitelist | b64enc }}
