apiVersion: v1
kind: Secret
metadata:
  name: {{ template "azure-industrial-iot.env.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: azure-industrial-iot-env
    app.kubernetes.io/part-of: azure-industrial-iot
type: Opaque
data:
{{- /* IoT Hub */}}
  PCS_IOTHUB_CONNSTRING: {{ required "A valid .Values.azure.iotHub.sharedAccessPolicies.iothubowner.connectionString is required!" .Values.azure.iotHub.sharedAccessPolicies.iothubowner.connectionString | b64enc }}
  PCS_IOTHUB_EVENTHUBENDPOINT: {{ required "A valid .Values.azure.iotHub.eventHub.endpoint is required!" .Values.azure.iotHub.eventHub.endpoint | b64enc }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup.events }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup.telemetry }}
  {{- if eq ( trim .Values.azure.iotHub.eventHub.consumerGroup.events ) ( trim .Values.azure.iotHub.eventHub.consumerGroup.telemetry ) }}
  {{- fail ".Values.azure.iotHub.eventHub.consumerGroup.events and .Values.azure.iotHub.eventHub.consumerGroup.telemetry should have different values!" }}
  {{- else }}
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_EVENTS: {{ required "A valid .Values.azure.iotHub.eventHub.consumerGroup.events is required!" .Values.azure.iotHub.eventHub.consumerGroup.events | b64enc }}
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_TELEMETRY: {{ required "A valid .Values.azure.iotHub.eventHub.consumerGroup.telemetry is required!" .Values.azure.iotHub.eventHub.consumerGroup.telemetry | b64enc }}
  {{- end }}
  {{- else }}
  {{- fail "A valid .Values.azure.iotHub.eventHub.consumerGroup.telemetry is required!" }}
  {{- end }}
  {{- else }}
  {{- fail "A valid .Values.azure.iotHub.eventHub.consumerGroup.events is required!" }}
  {{- end }}
  {{- else }}
  {{- fail "Valid .Values.azure.iotHub.eventHub.consumerGroup.events and .Values.azure.iotHub.eventHub.consumerGroup.telemetry are required!" }}
  {{- end }}
{{- /* Cosmos DB */}}
  PCS_COSMOSDB_CONNSTRING: {{ required "A valid .Values.azure.cosmosDB.connectionString is required!" .Values.azure.cosmosDB.connectionString | b64enc }}
{{- /* Storage Account */}}
  PCS_STORAGE_CONNSTRING: {{ required "A valid .Values.azure.storageAccount.connectionString is required!" .Values.azure.storageAccount.connectionString | b64enc }}
  {{- if .Values.azure.storageAccount.container }}
  {{- if .Values.azure.storageAccount.container.dataProtection }}
  {{- if .Values.azure.storageAccount.container.dataProtection.name }}
  PCS_STORAGE_CONTAINER_DATAPROTECTION: {{ .Values.azure.storageAccount.container.dataProtection.name | b64enc }}
  {{- else }}
  PCS_STORAGE_CONTAINER_DATAPROTECTION: ""
  {{- end }}
  {{- else }}
  PCS_STORAGE_CONTAINER_DATAPROTECTION: ""
  {{- end }}
  {{- else }}
  PCS_STORAGE_CONTAINER_DATAPROTECTION: ""
  {{- end }}
{{- /* ADLS Gen2 Storage Account */}}
  {{- if .Values.deployment.microServices.telemetryCdmProcessor.enabled }}
  PCS_ADLSG2_CONNSTRING: {{ required "A valid .Values.azure.adlsg2.connectionString is required!" .Values.azure.adlsg2.connectionString | b64enc }}
  PCS_ADLSG2_CONTAINER_CDM: {{ required "A valid .Values.azure.adlsg2.container.cdm.name is required!" .Values.azure.adlsg2.container.cdm.name | b64enc }}
  PCS_ADLSG2_CONTAINER_CDM_ROOTFOLDER: {{ required "A valid .Values.azure.adlsg2.container.cdm.rootFolder is required!" .Values.azure.adlsg2.container.cdm.rootFolder | b64enc }}
  {{- else }}
  PCS_ADLSG2_CONNSTRING: ""
  PCS_ADLSG2_CONTAINER_CDM: ""
  PCS_ADLSG2_CONTAINER_CDM_ROOTFOLDER: ""
  {{- end }}
{{- /* Event Hub Namespace and Event Hubs */}}
  PCS_EVENTHUB_CONNSTRING: {{ required "A valid .Values.azure.eventHubNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString is required!" .Values.azure.eventHubNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString | b64enc }}
  PCS_EVENTHUB_NAME: {{ required "A valid .Values.azure.eventHubNamespace.eventHub.name is required!" .Values.azure.eventHubNamespace.eventHub.name | b64enc }}
  {{- if .Values.azure.eventHubNamespace.eventHub.consumerGroup }}
  {{- if .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm }}
  {{- if .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx }}
  {{- if eq ( trim .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm ) ( trim .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx ) }}
  {{- fail ".Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm and .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx should have different values!" }}
  {{- else }}
  PCS_EVENTHUB_CONSUMERGROUP_TELEMETRY_CDM: {{ required "A valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm is required!" .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm | b64enc }}
  PCS_EVENTHUB_CONSUMERGROUP_TELEMETRY_UX: {{ required "A valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx is required!" .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx | b64enc }}
  {{- end }}
  {{- else }}
  {{- fail "A valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx is required!" }}
  {{- end }}
  {{- else }}
  {{- fail "A valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm is required!" }}
  {{- end }}
  {{- else }}
  {{- fail "Valid .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm and .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx are required!" }}
  {{- end }}
{{- /* Service Bus */}}
  PCS_SERVICEBUS_CONNSTRING: {{ required "A valid .Values.azure.serviceBusNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString is required!" .Values.azure.serviceBusNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString | b64enc }}
{{- /* Key Vault */}}
  PCS_KEYVAULT_URL: {{ required "A valid .Values.azure.keyVault.uri is required!" .Values.azure.keyVault.uri | b64enc }}
  {{- if .Values.azure.keyVault.key }}
  {{- if .Values.azure.keyVault.key.dataProtection }}
  PCS_KEYVAULT_KEY_DATAPROTECTION: {{ .Values.azure.keyVault.key.dataProtection | b64enc }}
  {{- else }}
  PCS_KEYVAULT_KEY_DATAPROTECTION: ""
  {{- end }}
  {{- else }}
  PCS_KEYVAULT_KEY_DATAPROTECTION: ""
  {{- end }}
  {{- if .Values.azure.auth.required }}
  PCS_KEYVAULT_APPID: {{ required "A valid .Values.azure.auth.servicesApp.appId is required!" .Values.azure.auth.servicesApp.appId | b64enc }}
  PCS_KEYVAULT_SECRET: {{ required "A valid .Values.azure.auth.servicesApp.secret is required!" .Values.azure.auth.servicesApp.secret | b64enc }}
  {{- else }}
  PCS_KEYVAULT_APPID: ""
  PCS_KEYVAULT_SECRET: ""
  {{- end }}
{{- /* Application Insights */}}
  {{- if .Values.azure.applicationInsights }}
  {{- if .Values.azure.applicationInsights.instrumentationKey }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.azure.applicationInsights.instrumentationKey | b64enc }}
  {{- else }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: ""
  {{- end }}
  {{- else }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: ""
  {{- end }}
{{- /* Service URLs */}}
  {{- if .Values.externalServiceUrl }}
  PCS_SERVICE_URL: {{ .Values.externalServiceUrl | trimSuffix "/" | b64enc }}
  {{- else }}
  PCS_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.registry.enabled }}
  {{- $service := include "azure-industrial-iot.registry.fullname" . }}
  {{- $port := .Values.deployment.microServices.registry.service.port }}
  PCS_TWIN_REGISTRY_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_TWIN_REGISTRY_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.twin.enabled }}
  {{- $service := include "azure-industrial-iot.twin.fullname" . }}
  {{- $port := .Values.deployment.microServices.twin.service.port }}
  PCS_TWIN_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_TWIN_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.history.enabled }}
  {{- $service := include "azure-industrial-iot.history.fullname" . }}
  {{- $port := .Values.deployment.microServices.history.service.port }}
  PCS_HISTORY_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_HISTORY_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.vault.enabled }}
  {{- $service := include "azure-industrial-iot.vault.fullname" . }}
  {{- $port := .Values.deployment.microServices.vault.service.port }}
  PCS_VAULT_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_VAULT_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.onboarding.enabled }}
  {{- $service := include "azure-industrial-iot.onboarding.fullname" . }}
  {{- $port := .Values.deployment.microServices.onboarding.service.port }}
  PCS_ONBOARDING_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_ONBOARDING_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.publisher.enabled }}
  {{- $service := include "azure-industrial-iot.publisher.fullname" . }}
  {{- $port := .Values.deployment.microServices.publisher.service.port }}
  PCS_PUBLISHER_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_PUBLISHER_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.publisherJobs.enabled }}
  {{- $service := include "azure-industrial-iot.publisher-jobs.fullname" . }}
  {{- $port := .Values.deployment.microServices.publisherJobs.service.port }}
  PCS_JOBS_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_JOBS_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.edgeJobs.enabled }}
  {{- if .Values.externalServiceUrl }}
  PCS_JOB_ORCHESTRATOR_SERVICE_URL: {{ printf "%s%s" ( trimSuffix "/" .Values.externalServiceUrl ) .Values.apps.urlPathBase.edgeJobs | b64enc }}
  {{- else }}
  {{- $service := include "azure-industrial-iot.edge-jobs.fullname" . }}
  {{- $port := .Values.deployment.microServices.edgeJobs.service.port }}
  PCS_JOB_ORCHESTRATOR_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- end }}
  {{- else }}
  PCS_JOB_ORCHESTRATOR_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.configuration.enabled }}
  {{- $service := include "azure-industrial-iot.configuration.fullname" . }}
  {{- $port := .Values.deployment.microServices.configuration.service.port }}
  PCS_CONFIGURATION_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_CONFIGURATION_SERVICE_URL: ""
  {{- end }}
{{- /* SignalR */}}
  PCS_SIGNALR_CONNSTRING: {{ required "A valid .Values.azure.signalR.connectionString is required!" .Values.azure.signalR.connectionString | b64enc }}
{{- /* Authentication */}}
  PCS_AUTH_TENANT: {{ required "A valid .Values.azure.tenantId is required!" .Values.azure.tenantId | b64enc }}
  PCS_AUTH_INSTANCE: {{ required "A valid .Values.azure.auth.authority is required!" .Values.azure.auth.authority | b64enc }}
  PCS_AUTH_ISSUER: {{ required "A valid .Values.azure.tenantId is required!" .Values.azure.tenantId | printf "https://sts.windows.net/%s/" | b64enc }}
  PCS_AUTH_HTTPSREDIRECTPORT: {{ "0" | b64enc }}
  {{- if .Values.azure.auth.required }}
  PCS_AUTH_REQUIRED: {{ .Values.azure.auth.required | printf "%t" | b64enc }}
  PCS_AUTH_AUDIENCE: {{ required "A valid .Values.azure.auth.servicesApp.audience is required!" .Values.azure.auth.servicesApp.audience | b64enc }}
  PCS_AUTH_CLIENT_APPID: {{ required "A valid .Values.azure.auth.clientsApp.appId is required!" .Values.azure.auth.clientsApp.appId | b64enc }}
  PCS_AUTH_CLIENT_SECRET: {{ required "A valid .Values.azure.auth.clientsApp.secret is required!" .Values.azure.auth.clientsApp.secret | b64enc }}
  PCS_AUTH_SERVICE_APPID: {{ required "A valid .Values.azure.auth.servicesApp.appId is required!" .Values.azure.auth.servicesApp.appId | b64enc }}
  PCS_AUTH_SERVICE_SECRET: {{ required "A valid .Values.azure.auth.servicesApp.secret is required!" .Values.azure.auth.servicesApp.secret | b64enc }}
  {{- else }}
  PCS_AUTH_REQUIRED: {{ false | printf "%t" | b64enc }}
  PCS_AUTH_AUDIENCE: ""
  PCS_AUTH_CLIENT_APPID: ""
  PCS_AUTH_CLIENT_SECRET: ""
  PCS_AUTH_SERVICE_APPID: ""
  PCS_AUTH_SERVICE_SECRET: ""
  {{- end }}
{{- /* CORS Whitelist */}}
  PCS_CORS_WHITELIST: {{ required "A valid .Values.azure.auth.corsWhitelist is required!" .Values.azure.auth.corsWhitelist | b64enc }}
{{- /* Service URL path bases */}}
  {{- if .Values.deployment.microServices.registry.enabled }}
  PCS_TWIN_REGISTRY_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.registry is required!" .Values.apps.urlPathBase.registry | b64enc }}
  {{- else }}
  PCS_TWIN_REGISTRY_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.twin.enabled }}
  PCS_TWIN_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.twin is required!" .Values.apps.urlPathBase.twin | b64enc }}
  {{- else }}
  PCS_TWIN_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.history.enabled }}
  PCS_HISTORY_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.history is required!" .Values.apps.urlPathBase.history | b64enc }}
  {{- else }}
  PCS_HISTORY_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.gateway.enabled }}
  PCS_GATEWAY_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.gateway is required!" .Values.apps.urlPathBase.gateway | b64enc }}
  {{- else }}
  PCS_GATEWAY_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.vault.enabled }}
  PCS_VAULT_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.vault is required!" .Values.apps.urlPathBase.vault | b64enc }}
  {{- else }}
  PCS_VAULT_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.onboarding.enabled }}
  PCS_ONBOARDING_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.onboarding is required!" .Values.apps.urlPathBase.onboarding | b64enc }}
  {{- else }}
  PCS_ONBOARDING_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.publisher.enabled }}
  PCS_PUBLISHER_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.publisher is required!" .Values.apps.urlPathBase.publisher | b64enc }}
  {{- else }}
  PCS_PUBLISHER_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.configuration.enabled }}
  PCS_CONFIGURATION_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.configuration is required!" .Values.apps.urlPathBase.configuration | b64enc }}
  {{- else }}
  PCS_CONFIGURATION_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.edgeManager.enabled }}
  PCS_EDGE_MANAGER_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.edgeManager is required!" .Values.apps.urlPathBase.edgeManager | b64enc }}
  {{- else }}
  PCS_EDGE_MANAGER_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.engineeringTool.enabled }}
  PCS_FRONTEND_APP_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.engineeringTool is required!" .Values.apps.urlPathBase.engineeringTool | b64enc }}
  {{- else }}
  PCS_FRONTEND_APP_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.edgeJobs.enabled }}
  PCS_JOB_ORCHESTRATOR_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.edgeJobs is required!" .Values.apps.urlPathBase.edgeJobs | b64enc }}
  {{- else }}
  PCS_JOB_ORCHESTRATOR_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.publisherJobs.enabled }}
  PCS_JOBS_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.publisherJobs is required!" .Values.apps.urlPathBase.publisherJobs | b64enc }}
  {{- else }}
  PCS_JOBS_SERVICE_PATH_BASE: ""
  {{- end }}
{{- /* AspNetCore */}}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: {{ .Values.apps.aspNetCore.forwardedHeaders.enabled | printf "%t" | b64enc }}
  ASPNETCORE_FORWARDEDHEADERS_FORWARDLIMIT: {{ .Values.apps.aspNetCore.forwardedHeaders.forwardLimit | toString | b64enc }}
{{- /* OpenAPI */}}
  {{- if .Values.apps.openApi.serverHost }}
  PCS_OPENAPI_SERVER_HOST: {{ .Values.apps.openApi.serverHost | trimPrefix "http://" | trimPrefix "https://" | trimSuffix "/" | b64enc }}
  {{- else }}
  PCS_OPENAPI_SERVER_HOST: ""
  {{- end }}
