{{- if .Values.loadConfFromKeyVaul }}
{{- /*
In this case microservices should load application configuration parameters from Azure Key Vault.
This means that there are only a few required values in this case.
*/}}
{{- if not .Values.azure.auth.required }}
{{- fail ".Values.azure.auth.required cannot be false if .Values.loadConfFromKeyVaul is true as details of .Values.azure.auth.servicesApp are required!" }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "azure-industrial-iot.env.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: azure-industrial-iot-env
    app.kubernetes.io/part-of: azure-industrial-iot
type: Opaque
data:
{{- /* IoT Hub */}}
  {{- if .Values.azure.iotHub.sharedAccessPolicies.iothubowner.connectionString }}
  PCS_IOTHUB_CONNSTRING: {{ .Values.azure.iotHub.sharedAccessPolicies.iothubowner.connectionString | b64enc }}
  {{- end }}
  {{- if .Values.azure.iotHub.eventHub.endpoint }}
  PCS_IOTHUB_EVENTHUBENDPOINT: {{ .Values.azure.iotHub.eventHub.endpoint | b64enc }}
  {{- end }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup.events }}
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_EVENTS: {{ .Values.azure.iotHub.eventHub.consumerGroup.events | b64enc }}
  {{- end }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup.telemetry }}
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_TELEMETRY: {{ .Values.azure.iotHub.eventHub.consumerGroup.telemetry | b64enc }}
  {{- end }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup.tunnel }}
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_TUNNEL: {{ .Values.azure.iotHub.eventHub.consumerGroup.tunnel | b64enc }}
  {{- end }}
  {{- if .Values.azure.iotHub.eventHub.consumerGroup.onboarding }}
  PCS_IOTHUB_EVENTHUB_CONSUMER_GROUP_ONBOARDING: {{ .Values.azure.iotHub.eventHub.consumerGroup.onboarding | b64enc }}
  {{- end }}
{{- /* Cosmos DB */}}
  {{- if .Values.azure.cosmosDB.connectionString }}
  PCS_COSMOSDB_CONNSTRING: {{ .Values.azure.cosmosDB.connectionString | b64enc }}
  {{- end }}
{{- /* Storage Account */}}
  {{- if .Values.azure.storageAccount.connectionString }}
  PCS_STORAGE_CONNSTRING: {{ .Values.azure.storageAccount.connectionString | b64enc }}
  {{- end }}
  {{- if .Values.azure.storageAccount.container.dataProtection.name }}
  PCS_STORAGE_CONTAINER_DATAPROTECTION: {{ .Values.azure.storageAccount.container.dataProtection.name | b64enc }}
  {{- end }}
{{- /* ADLS Gen2 Storage Account */}}
  {{- if .Values.azure.adlsg2.connectionString }}
  PCS_ADLSG2_CONNSTRING: {{ .Values.azure.adlsg2.connectionString | b64enc }}
  {{- end }}
  {{- if .Values.azure.adlsg2.container.cdm.name }}
  PCS_ADLSG2_CONTAINER_CDM: {{ .Values.azure.adlsg2.container.cdm.name | b64enc }}
  {{- end }}
  {{- if .Values.azure.adlsg2.container.cdm.rootFolder }}
  PCS_ADLSG2_CONTAINER_CDM_ROOTFOLDER: {{ .Values.azure.adlsg2.container.cdm.rootFolder | b64enc }}
  {{- end }}
{{- /* Event Hub Namespace and Event Hubs */}}
  {{- if .Values.azure.eventHubNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString }}
  PCS_EVENTHUB_CONNSTRING: {{ .Values.azure.eventHubNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString | b64enc }}
  {{- end }}
  {{- if .Values.azure.eventHubNamespace.eventHub.name }}
  PCS_EVENTHUB_NAME: {{ .Values.azure.eventHubNamespace.eventHub.name | b64enc }}
  {{- end }}
  {{- if .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm }}
  PCS_EVENTHUB_CONSUMERGROUP_TELEMETRY_CDM: {{ .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryCdm | b64enc }}
  {{- end }}
  {{- if .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx }}
  PCS_EVENTHUB_CONSUMERGROUP_TELEMETRY_UX: {{ .Values.azure.eventHubNamespace.eventHub.consumerGroup.telemetryUx | b64enc }}
  {{- end }}
{{- /* Service Bus */}}
  {{- if .Values.azure.serviceBusNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString }}
  PCS_SERVICEBUS_CONNSTRING: {{ .Values.azure.serviceBusNamespace.sharedAccessPolicies.rootManageSharedAccessKey.connectionString | b64enc }}
  {{- end }}
{{- /* Key Vault */}}
  PCS_KEYVAULT_URL: {{ required "A valid .Values.azure.keyVault.uri is required!" .Values.azure.keyVault.uri | b64enc }}
  {{- if .Values.azure.keyVault.key.dataProtection }}
  PCS_KEYVAULT_KEY_DATAPROTECTION: {{ .Values.azure.keyVault.key.dataProtection | b64enc }}
  {{- end }}
  PCS_KEYVAULT_APPID: {{ required "A valid .Values.azure.auth.servicesApp.appId is required!" .Values.azure.auth.servicesApp.appId | b64enc }}
  PCS_KEYVAULT_SECRET: {{ required "A valid .Values.azure.auth.servicesApp.secret is required!" .Values.azure.auth.servicesApp.secret | b64enc }}
{{- /* Application Insights */}}
  {{- if .Values.azure.applicationInsights.instrumentationKey }}
  PCS_APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.azure.applicationInsights.instrumentationKey | b64enc }}
  {{- end }}
{{- /* Log Analytics Workspace */}}
  {{- if .Values.azure.logAnalyticsWorkspace.id }}
  PCS_WORKSPACE_ID: {{  .Values.azure.logAnalyticsWorkspace.id | b64enc }}
  {{- end }}
  {{- if .Values.azure.logAnalyticsWorkspace.key }}
  PCS_WORKSPACE_KEY: {{ .Values.azure.logAnalyticsWorkspace.key | b64enc }}
  {{- end }}
{{- /* Service URLs */}}
  {{- if .Values.externalServiceUrl }}
  PCS_SERVICE_URL: {{ .Values.externalServiceUrl | trimSuffix "/" | b64enc }}
  {{- end }}
  {{- if .Values.deployment.microServices.registry.enabled }}
  {{- $service := include "azure-industrial-iot.registry.fullname" . }}
  {{- $port := .Values.deployment.microServices.registry.service.port }}
  PCS_TWIN_REGISTRY_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_TWIN_REGISTRY_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.twin.enabled }}
  {{- $service := include "azure-industrial-iot.twin.fullname" . }}
  {{- $port := .Values.deployment.microServices.twin.service.port }}
  PCS_TWIN_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_TWIN_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.history.enabled }}
  {{- $service := include "azure-industrial-iot.history.fullname" . }}
  {{- $port := .Values.deployment.microServices.history.service.port }}
  PCS_HISTORY_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_HISTORY_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.vault.enabled }}
  {{- $service := include "azure-industrial-iot.vault.fullname" . }}
  {{- $port := .Values.deployment.microServices.vault.service.port }}
  PCS_VAULT_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_VAULT_SERVICE_URL: ""
  {{- end }}
  {{- if .Values.deployment.microServices.publisher.enabled }}
  {{- $service := include "azure-industrial-iot.publisher.fullname" . }}
  {{- $port := .Values.deployment.microServices.publisher.service.port }}
  PCS_PUBLISHER_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_PUBLISHER_SERVICE_URL: ""
  {{- end }}
  {{- if and .Values.deployment.microServices.edgeJobs.enabled .Values.externalServiceUrl }}
  PCS_PUBLISHER_ORCHESTRATOR_SERVICE_URL: {{ printf "%s%s" ( trimSuffix "/" .Values.externalServiceUrl ) .Values.apps.urlPathBase.edgeJobs | b64enc }}
  {{- end }}
  {{- if .Values.deployment.microServices.events.enabled }}
  {{- $service := include "azure-industrial-iot.events.fullname" . }}
  {{- $port := .Values.deployment.microServices.events.service.port }}
  PCS_EVENTS_SERVICE_URL: {{ printf "http://%s.%s:%s" $service .Release.Namespace ( toString $port ) | b64enc }}
  {{- else }}
  PCS_EVENTS_SERVICE_URL: ""
  {{- end }}
{{- /* SignalR */}}
  {{- if .Values.azure.signalR.connectionString }}
  PCS_SIGNALR_CONNSTRING: {{ .Values.azure.signalR.connectionString | b64enc }}
  {{- end }}
  {{- if .Values.azure.signalR.serviceMode }}
  PCS_SIGNALR_MODE: {{ .Values.azure.signalR.serviceMode | b64enc }}
  {{- end }}
{{- /* Authentication */}}
  PCS_AUTH_TENANT: {{ required "A valid .Values.azure.tenantId is required!" .Values.azure.tenantId | b64enc }}
  {{- if .Values.azure.auth.authority }}
  PCS_AUTH_INSTANCE: {{ .Values.azure.auth.authority | b64enc }}
  {{- end }}
  PCS_AUTH_ISSUER: {{ .Values.azure.tenantId | printf "https://sts.windows.net/%s/" | b64enc }}
  PCS_AUTH_HTTPSREDIRECTPORT: {{ "0" | b64enc }}
  PCS_AUTH_REQUIRED: {{ .Values.azure.auth.required | printf "%t" | b64enc }}
  {{- if .Values.azure.auth.servicesApp.audience }}
  PCS_AUTH_AUDIENCE: {{ .Values.azure.auth.servicesApp.audience | b64enc }}
  {{- end }}
  {{- if .Values.azure.auth.clientsApp.appId }}
  PCS_AUTH_CLIENT_APPID: {{ .Values.azure.auth.clientsApp.appId | b64enc }}
  {{- end }}
  {{- if .Values.azure.auth.clientsApp.secret }}
  PCS_AUTH_CLIENT_SECRET: {{ .Values.azure.auth.clientsApp.secret | b64enc }}
  {{- end }}
  {{- if .Values.azure.auth.servicesApp.appId }}
  PCS_AUTH_SERVICE_APPID: {{ .Values.azure.auth.servicesApp.appId | b64enc }}
  {{- end }}
  {{- if .Values.azure.auth.servicesApp.secret }}
  PCS_AUTH_SERVICE_SECRET: {{ .Values.azure.auth.servicesApp.secret | b64enc }}
  {{- end }}
{{- /* CORS Whitelist */}}
  {{- if .Values.azure.auth.corsWhitelist }}
  PCS_CORS_WHITELIST: {{ .Values.azure.auth.corsWhitelist | b64enc }}
  {{- end }}
{{- /* Service URL path bases */}}
  {{- if .Values.deployment.microServices.registry.enabled }}
  PCS_TWIN_REGISTRY_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.registry is required!" .Values.apps.urlPathBase.registry | b64enc }}
  {{- else }}
  PCS_TWIN_REGISTRY_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.twin.enabled }}
  PCS_TWIN_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.twin is required!" .Values.apps.urlPathBase.twin | b64enc }}
  {{- else }}
  PCS_TWIN_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.history.enabled }}
  PCS_HISTORY_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.history is required!" .Values.apps.urlPathBase.history | b64enc }}
  {{- else }}
  PCS_HISTORY_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.gateway.enabled }}
  PCS_GATEWAY_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.gateway is required!" .Values.apps.urlPathBase.gateway | b64enc }}
  {{- else }}
  PCS_GATEWAY_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.vault.enabled }}
  PCS_VAULT_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.vault is required!" .Values.apps.urlPathBase.vault | b64enc }}
  {{- else }}
  PCS_VAULT_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.publisher.enabled }}
  PCS_PUBLISHER_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.publisher is required!" .Values.apps.urlPathBase.publisher | b64enc }}
  {{- else }}
  PCS_PUBLISHER_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.events.enabled }}
  PCS_EVENTS_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.events is required!" .Values.apps.urlPathBase.events | b64enc }}
  {{- else }}
  PCS_EVENTS_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.engineeringTool.enabled }}
  PCS_FRONTEND_APP_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.engineeringTool is required!" .Values.apps.urlPathBase.engineeringTool | b64enc }}
  {{- else }}
  PCS_FRONTEND_APP_SERVICE_PATH_BASE: ""
  {{- end }}
  {{- if .Values.deployment.microServices.edgeJobs.enabled }}
  PCS_PUBLISHER_ORCHESTRATOR_SERVICE_PATH_BASE: {{ required "A valid .Values.apps.urlPathBase.edgeJobs is required!" .Values.apps.urlPathBase.edgeJobs | b64enc }}
  {{- else }}
  PCS_PUBLISHER_ORCHESTRATOR_SERVICE_PATH_BASE: ""
  {{- end }}
{{- /* AspNetCore */}}
  {{- if .Values.apps.aspNetCore.forwardedHeaders.enabled }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: {{ .Values.apps.aspNetCore.forwardedHeaders.enabled | printf "%t" | b64enc }}
  {{- end }}
  {{- if .Values.apps.aspNetCore.forwardedHeaders.forwardLimit }}
  ASPNETCORE_FORWARDEDHEADERS_FORWARDLIMIT: {{ .Values.apps.aspNetCore.forwardedHeaders.forwardLimit | toString | b64enc }}
  {{- end }}
{{- /* OpenAPI */}}
  {{- if .Values.apps.openApi.serverHost }}
  PCS_OPENAPI_SERVER_HOST: {{ .Values.apps.openApi.serverHost | trimPrefix "http://" | trimPrefix "https://" | trimSuffix "/" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
