{{- if .Values.deployment.microServices.registry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "azure-industrial-iot.registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: opc-registry
    app.kubernetes.io/part-of: azure-industrial-iot
{{- if .Values.deployment.microServices.registry.extraLabels }}
{{ toYaml .Values.deployment.microServices.registry.extraLabels | indent 4 }}
{{- end }}
{{- if .Values.deployment.microServices.registry.service.annotations }}
  annotations:
{{ toYaml .Values.deployment.microServices.registry.service.annotations | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: opc-registry
    app.kubernetes.io/part-of: azure-industrial-iot
  ports:
  - port: 443
    protocol: TCP
    name: https
  - port: 9042
    protocol: TCP
    name: rest
{{- end }}
