{{- if .Values.deployment.microServices.alerting.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "azure-industrial-iot.alerting.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: opc-alerting
    app.kubernetes.io/part-of: azure-industrial-iot
spec:
  replicas: {{ .Values.deployment.microServices.alerting.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: opc-alerting
      app.kubernetes.io/part-of: azure-industrial-iot
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: opc-alerting
        app.kubernetes.io/part-of: azure-industrial-iot
    spec:
      # serviceAccountName: industrial-iot-serviceaccount
      containers:
      - name: alerting-service-container
        image: {{ .Values.Image.Registry }}/opc-alerting-service:{{ .Values.Image.Tag }}
        imagePullPolicy: {{ .Values.Image.PullPolicy }}
        {{- if .Values.deployment.microServices.alerting.extraArgs }}
        args:
          {{- range .Values.deployment.microServices.alerting.extraArgs }}
          - {{ . }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.deployment.microServices.alerting.resources.requests.memory }}
            cpu: {{ .Values.deployment.microServices.alerting.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.microServices.alerting.resources.limits.memory }}
            cpu: {{ .Values.deployment.microServices.alerting.resources.limits.cpu }}
        env:
        - name: PCS_KEYVAULT_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_KEYVAULT_URL
        - name: PCS_WORKSPACE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_WORKSPACE_NAME
        - name: PCS_IOTHUB_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_IOTHUB_CONNSTRING
        - name: PCS_SERVICEBUS_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_SERVICEBUS_CONNSTRING
        - name: PCS_APPINSIGHTS_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_APPINSIGHTS_NAME
        - name: PCS_APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_APPINSIGHTS_INSTRUMENTATIONKEY
{{- end }}
