// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
//  Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
// ------------------------------------------------------------

namespace Azure.IIoT.OpcUa.Publisher.Models
{
    using Azure.IIoT.OpcUa.Core.Serialization;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.CompilerServices;
    using System.Text.Json;
    using System.Text.Json.Nodes;
    using System.Text.Json.Serialization;
    using System.Text.Json.Serialization.Metadata;

    /// <summary>
    /// Source generated metadata for the public Publisher REST contract.
    /// </summary>
    [JsonSourceGenerationOptions(
        GenerationMode = JsonSourceGenerationMode.Metadata,
        PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
        UseStringEnumConverter = true)]
    [JsonSerializable(typeof(AdditionalData))]
    [JsonSerializable(typeof(AggregateConfigurationModel))]
    [JsonSerializable(typeof(AggregateFilterModel))]
    [JsonSerializable(typeof(ApplicationInfoModel))]
    [JsonSerializable(typeof(ApplicationRegistrationModel))]
    [JsonSerializable(typeof(ApplicationType))]
    [JsonSerializable(typeof(AttributeReadRequestModel))]
    [JsonSerializable(typeof(AttributeReadResponseModel))]
    [JsonSerializable(typeof(AttributeWriteRequestModel))]
    [JsonSerializable(typeof(AttributeWriteResponseModel))]
    [JsonSerializable(typeof(AuthenticationMethodModel))]
    [JsonSerializable(typeof(BrowseDirection))]
    [JsonSerializable(typeof(BrowseFirstRequestModel))]
    [JsonSerializable(typeof(BrowseFirstResponseModel))]
    [JsonSerializable(typeof(BrowseNextRequestModel))]
    [JsonSerializable(typeof(BrowseNextResponseModel))]
    [JsonSerializable(typeof(BrowsePathRequestModel))]
    [JsonSerializable(typeof(BrowsePathResponseModel))]
    [JsonSerializable(typeof(BrowseStreamChunkModel))]
    [JsonSerializable(typeof(BrowseStreamRequestModel))]
    [JsonSerializable(typeof(BrowseViewModel))]
    [JsonSerializable(typeof(CertificateStoreName))]
    [JsonSerializable(typeof(ChannelDiagnosticModel))]
    [JsonSerializable(typeof(ChannelKeyModel))]
    [JsonSerializable(typeof(ConditionHandlingOptionsModel))]
    [JsonSerializable(typeof(ConnectionDiagnosticsModel))]
    [JsonSerializable(typeof(ConnectionModel))]
    [JsonSerializable(typeof(ConnectionOptions))]
    [JsonSerializable(typeof(ContentFilterElementModel))]
    [JsonSerializable(typeof(ContentFilterModel))]
    [JsonSerializable(typeof(CredentialModel))]
    [JsonSerializable(typeof(CredentialType))]
    [JsonSerializable(typeof(DataChangeFilterModel))]
    [JsonSerializable(typeof(DataChangeTriggerType))]
    [JsonSerializable(typeof(DataLocation))]
    [JsonSerializable(typeof(DataSetFieldContentFlags))]
    [JsonSerializable(typeof(DataSetMessageContentFlags))]
    [JsonSerializable(typeof(DataSetMetaDataModel))]
    [JsonSerializable(typeof(DataSetOrderingType))]
    [JsonSerializable(typeof(DataSetRoutingMode))]
    [JsonSerializable(typeof(DataSetWriterMessageSettingsModel))]
    [JsonSerializable(typeof(DataSetWriterModel))]
    [JsonSerializable(typeof(DataSetWriterStateDiagnosticModel))]
    [JsonSerializable(typeof(DataTypeMetadataModel))]
    [JsonSerializable(typeof(DeadbandType))]
    [JsonSerializable(typeof(DeleteEventsDetailsModel))]
    [JsonSerializable(typeof(DeleteValuesAtTimesDetailsModel))]
    [JsonSerializable(typeof(DeleteValuesDetailsModel))]
    [JsonSerializable(typeof(DiagnosticsLevel))]
    [JsonSerializable(typeof(DiagnosticsModel))]
    [JsonSerializable(typeof(DiscoveryCancelRequestModel))]
    [JsonSerializable(typeof(DiscoveryConfigModel))]
    [JsonSerializable(typeof(DiscoveryEventModel))]
    [JsonSerializable(typeof(DiscoveryMode))]
    [JsonSerializable(typeof(DiscoveryProgressModel))]
    [JsonSerializable(typeof(DiscoveryProgressType))]
    [JsonSerializable(typeof(DiscoveryRequestModel))]
    [JsonSerializable(typeof(DiscoveryResultModel))]
    [JsonSerializable(typeof(EndpointConnectivityState))]
    [JsonSerializable(typeof(EndpointEventModel))]
    [JsonSerializable(typeof(EndpointEventType))]
    [JsonSerializable(typeof(EndpointInfoModel))]
    [JsonSerializable(typeof(EndpointModel))]
    [JsonSerializable(typeof(EndpointRegistrationModel))]
    [JsonSerializable(typeof(EnumDescriptionModel))]
    [JsonSerializable(typeof(EnumFieldDescriptionModel))]
    [JsonSerializable(typeof(EventFilterModel))]
    [JsonSerializable(typeof(ExceptionDeviationType))]
    [JsonSerializable(typeof(FileInfoModel))]
    [JsonSerializable(typeof(FileOpenWriteOptionsModel))]
    [JsonSerializable(typeof(FileSystemObjectModel))]
    [JsonSerializable(typeof(FileWriteMode))]
    [JsonSerializable(typeof(FilterOperandModel))]
    [JsonSerializable(typeof(FilterOperatorType))]
    [JsonSerializable(typeof(GetConfiguredEndpointsRequestModel))]
    [JsonSerializable(typeof(GetConfiguredEndpointsResponseModel))]
    [JsonSerializable(typeof(GetConfiguredNodesOnEndpointResponseModel))]
    [JsonSerializable(typeof(HeartbeatBehavior))]
    [JsonSerializable(typeof(HistoricEventModel))]
    [JsonSerializable(typeof(HistoricValueModel))]
    [JsonSerializable(typeof(HistoryConfigurationModel))]
    [JsonSerializable(typeof(HistoryConfigurationRequestModel))]
    [JsonSerializable(typeof(HistoryConfigurationResponseModel))]
    [JsonSerializable(typeof(HistoryReadNextResponseModel<HistoricEventModel[]>))]
    [JsonSerializable(typeof(HistoryReadNextResponseModel<HistoricValueModel[]>))]
    [JsonSerializable(typeof(HistoryReadNextResponseModel<JsonNode>))]
    [JsonSerializable(typeof(HistoryReadRequestModel<ReadEventsDetailsModel>))]
    [JsonSerializable(typeof(HistoryReadRequestModel<ReadModifiedValuesDetailsModel>))]
    [JsonSerializable(typeof(HistoryReadRequestModel<ReadProcessedValuesDetailsModel>))]
    [JsonSerializable(typeof(HistoryReadRequestModel<ReadValuesAtTimesDetailsModel>))]
    [JsonSerializable(typeof(HistoryReadRequestModel<ReadValuesDetailsModel>))]
    [JsonSerializable(typeof(HistoryReadRequestModel<JsonNode>))]
    [JsonSerializable(typeof(HistoryReadResponseModel<HistoricEventModel[]>))]
    [JsonSerializable(typeof(HistoryReadResponseModel<HistoricValueModel[]>))]
    [JsonSerializable(typeof(HistoryReadResponseModel<JsonNode>))]
    [JsonSerializable(typeof(HistoryReadNextRequestModel))]
    [JsonSerializable(typeof(HistoryServerCapabilitiesModel))]
    [JsonSerializable(typeof(HistoryUpdateOperation))]
    [JsonSerializable(typeof(HistoryUpdateRequestModel<DeleteEventsDetailsModel>))]
    [JsonSerializable(typeof(HistoryUpdateRequestModel<DeleteValuesAtTimesDetailsModel>))]
    [JsonSerializable(typeof(HistoryUpdateRequestModel<DeleteValuesDetailsModel>))]
    [JsonSerializable(typeof(HistoryUpdateRequestModel<UpdateEventsDetailsModel>))]
    [JsonSerializable(typeof(HistoryUpdateRequestModel<UpdateValuesDetailsModel>))]
    [JsonSerializable(typeof(HistoryUpdateRequestModel<JsonNode>))]
    [JsonSerializable(typeof(HistoryUpdateResponseModel))]
    [JsonSerializable(typeof(InstanceDeclarationModel))]
    [JsonSerializable(typeof(LocalizedTextModel))]
    [JsonSerializable(typeof(MessageEncoding))]
    [JsonSerializable(typeof(MessageTimestamp))]
    [JsonSerializable(typeof(MessagingMode))]
    [JsonSerializable(typeof(MethodCallArgumentModel))]
    [JsonSerializable(typeof(MethodCallRequestModel))]
    [JsonSerializable(typeof(MethodCallResponseModel))]
    [JsonSerializable(typeof(MethodMetadataArgumentModel))]
    [JsonSerializable(typeof(MethodMetadataModel))]
    [JsonSerializable(typeof(MethodMetadataRequestModel))]
    [JsonSerializable(typeof(MethodMetadataResponseModel))]
    [JsonSerializable(typeof(ModelChangeHandlingOptionsModel))]
    [JsonSerializable(typeof(ModificationInfoModel))]
    [JsonSerializable(typeof(MonitoredItemNodeErrorModel))]
    [JsonSerializable(typeof(MonitoredItemWatchdogCondition))]
    [JsonSerializable(typeof(MonitoringMode))]
    [JsonSerializable(typeof(NamespaceFormat))]
    [JsonSerializable(typeof(NetworkMessageContentFlags))]
    [JsonSerializable(typeof(NodeAccessLevel))]
    [JsonSerializable(typeof(NodeAccessRestrictions))]
    [JsonSerializable(typeof(NodeAttribute))]
    [JsonSerializable(typeof(NodeClass))]
    [JsonSerializable(typeof(NodeEventNotifier))]
    [JsonSerializable(typeof(NodeIdModel))]
    [JsonSerializable(typeof(NodeMetadataRequestModel))]
    [JsonSerializable(typeof(NodeMetadataResponseModel))]
    [JsonSerializable(typeof(NodeModel))]
    [JsonSerializable(typeof(NodePathTargetModel))]
    [JsonSerializable(typeof(NodeReferenceModel))]
    [JsonSerializable(typeof(NodeType))]
    [JsonSerializable(typeof(NodeValueRank))]
    [JsonSerializable(typeof(OpcAuthenticationMode))]
    [JsonSerializable(typeof(OpcNodeModel))]
    [JsonSerializable(typeof(OperationContextModel))]
    [JsonSerializable(typeof(OperationLimitsModel))]
    [JsonSerializable(typeof(PublishBulkRequestModel))]
    [JsonSerializable(typeof(PublishBulkResponseModel))]
    [JsonSerializable(typeof(PublishDiagnosticInfoModel))]
    [JsonSerializable(typeof(PublishedDataItemsModel))]
    [JsonSerializable(typeof(PublishedDataSetEventModel))]
    [JsonSerializable(typeof(PublishedDataSetMessageSchemaModel))]
    [JsonSerializable(typeof(PublishedDataSetMetaDataModel))]
    [JsonSerializable(typeof(PublishedDataSetMethodModel))]
    [JsonSerializable(typeof(PublishedDataSetModel))]
    [JsonSerializable(typeof(PublishedDataSetSettingsModel))]
    [JsonSerializable(typeof(PublishedDataSetSourceDiagnosticModel))]
    [JsonSerializable(typeof(PublishedDataSetSourceModel))]
    [JsonSerializable(typeof(PublishedDataSetTriggerModel))]
    [JsonSerializable(typeof(PublishedDataSetVariableModel))]
    [JsonSerializable(typeof(PublishedEventItemsModel))]
    [JsonSerializable(typeof(PublishedFieldMetaDataModel))]
    [JsonSerializable(typeof(PublishedItemListRequestModel))]
    [JsonSerializable(typeof(PublishedItemListResponseModel))]
    [JsonSerializable(typeof(PublishedItemModel))]
    [JsonSerializable(typeof(PublishedMethodItemsModel))]
    [JsonSerializable(typeof(PublishedNodeDeleteAssetRequestModel))]
    [JsonSerializable(typeof(PublishedNodeExpansionModel))]
    [JsonSerializable(typeof(PublishedNodesEntryModel))]
    [JsonSerializable(typeof(List<PublishedNodesEntryModel>))]
    [JsonSerializable(typeof(IEnumerable<PublishedNodesEntryModel>))]
    [JsonSerializable(typeof(PublisherDiagnosticTargetType))]
    [JsonSerializable(typeof(PublishingQueueSettingsModel))]
    [JsonSerializable(typeof(PublishStartRequestModel))]
    [JsonSerializable(typeof(PublishStartResponseModel))]
    [JsonSerializable(typeof(PublishStopRequestModel))]
    [JsonSerializable(typeof(PublishStopResponseModel))]
    [JsonSerializable(typeof(QueryCompilationRequestModel))]
    [JsonSerializable(typeof(QueryCompilationResponseModel))]
    [JsonSerializable(typeof(QueryType))]
    [JsonSerializable(typeof(ReadEventsDetailsModel))]
    [JsonSerializable(typeof(ReadModifiedValuesDetailsModel))]
    [JsonSerializable(typeof(ReadProcessedValuesDetailsModel))]
    [JsonSerializable(typeof(ReadRequestModel))]
    [JsonSerializable(typeof(ReadResponseModel))]
    [JsonSerializable(typeof(ReadValuesAtTimesDetailsModel))]
    [JsonSerializable(typeof(ReadValuesDetailsModel))]
    [JsonSerializable(typeof(RelativePathElementModel))]
    [JsonSerializable(typeof(RequestHeaderModel))]
    [JsonSerializable(typeof(RolePermissionModel))]
    [JsonSerializable(typeof(RolePermissions))]
    [JsonSerializable(typeof(RuntimeStateEventModel))]
    [JsonSerializable(typeof(RuntimeStateEventType))]
    [JsonSerializable(typeof(SecurityMode))]
    [JsonSerializable(typeof(ServerCapabilitiesModel))]
    [JsonSerializable(typeof(ServerEndpointQueryModel))]
    [JsonSerializable(typeof(ServerRegistrationRequestModel))]
    [JsonSerializable(typeof(ServiceCounterModel))]
    [JsonSerializable(typeof(ServiceResultModel))]
    [JsonSerializable(typeof(SessionDiagnosticsModel))]
    [JsonSerializable(typeof(SetConfiguredEndpointsRequestModel))]
    [JsonSerializable(typeof(SetEndpointConfigurationRequestModel))]
    [JsonSerializable(typeof(SimpleAttributeOperandModel))]
    [JsonSerializable(typeof(SimpleTypeDescriptionModel))]
    [JsonSerializable(typeof(StructureFieldDescriptionModel))]
    [JsonSerializable(typeof(StructureType))]
    [JsonSerializable(typeof(SubscriptionDiagnosticsModel))]
    [JsonSerializable(typeof(SubscriptionWatchdogBehavior))]
    [JsonSerializable(typeof(TestConnectionRequestModel))]
    [JsonSerializable(typeof(TestConnectionResponseModel))]
    [JsonSerializable(typeof(TimestampsToReturn))]
    [JsonSerializable(typeof(TypeDefinitionModel))]
    [JsonSerializable(typeof(UpdateEventsDetailsModel))]
    [JsonSerializable(typeof(UpdateValuesDetailsModel))]
    [JsonSerializable(typeof(UserIdentityModel))]
    [JsonSerializable(typeof(ValueEncoding))]
    [JsonSerializable(typeof(ValueReadRequestModel))]
    [JsonSerializable(typeof(ValueReadResponseModel))]
    [JsonSerializable(typeof(ValueWriteRequestModel))]
    [JsonSerializable(typeof(ValueWriteResponseModel))]
    [JsonSerializable(typeof(VariableMetadataModel))]
    [JsonSerializable(typeof(WriteRequestModel))]
    [JsonSerializable(typeof(WriteResponseModel))]
    [JsonSerializable(typeof(WriterGroupDiagnosticModel))]
    [JsonSerializable(typeof(WriterGroupMessageSettingsModel))]
    [JsonSerializable(typeof(WriterGroupModel))]
    [JsonSerializable(typeof(WriterGroupStateDiagnosticModel))]
    [JsonSerializable(typeof(WriterGroupTransport))]
    [JsonSerializable(typeof(X509CertificateChainModel))]
    [JsonSerializable(typeof(X509CertificateModel))]
    [JsonSerializable(typeof(X509ChainStatus))]
    internal sealed partial class PublisherModelsJsonContext : JsonSerializerContext
    {
    }

    internal static class PublisherModelsJsonRegistration
    {
        [ModuleInitializer]
        [SuppressMessage("Usage", "CA2255",
            Justification = "The module initializer registers this assembly's " +
                "source-generated metadata before its contracts are serialized.")]
        internal static void Register()
        {
            Json.RegisterTypeInfoResolver(PublisherModelsJsonContext.Default);
        }
    }
}
